package com.asia.internal.errcode;

/**
 * 基础类错误信息（不带工号错误码）
 *
 * @author manco
 * @since 2019/03/11 15:08
 */
public enum ErrorCodePublicEnum implements IErrorCodeEnum {
    SUCCESS("0", "成功"),
    ERROR("error ", "待完错误描述"),
    NO_ERROR("0", "处理正确 "),
    CHANNEL_ID_NO_FOUND("2001", "渠道为空"),
    PAY_SERIALNUMBER_IS_EXIST("1405", "缴费流水已经存在"),
    DB_INSERT_ERROR("4102", "数据插入失败"),
    DB_UPDATE_ERROR("6010", "冲正更新数据库失败"),
    DATA_NOT_FOUND_INT("1", "数据未找到 "),
    UNKNOWN_ERROR("2", "不明错误 "),
    ERROR_SUCCESS("NO_ERROR", "待完错误描述"),
    ERROR_CONNECT_FAIL("1000", "待完错误描述"),
    ERROR_ROUTE_FAIL("1001", "待完错误描述"),
    ERROR_USERINFO_MIS("2000", "待完错误描述"),
    ERROR_BILLINGMODE_ERR("2001", "待完错误描述"),
    ERROR_USER_INVALID("2002", "待完错误描述"),
    ERROR_OFFER_INVALID("2010", "待完错误描述"),
    ERROR_ACCTITEM_MIS("3000", "待完错误描述"),
    ERROR_BILLING_CYCLE("4000", "待完错误描述"),
    ERROR_OFFERID_MIS("4002", "待完错误描述"),
    ERROR_DATABASE_OTHER("5000", "待完错误描述"),
    ERROR_INDB_ABNOR("6000", "待完错误描述"),
    DATA_NOT_FOUND("1", "数据未找到 "),
    CONNECT_DATABASE_ERROR("2", "连接数据出错 "),
    ORACLE_USER_NOT_EXIST("3", "数据库用户不存在 "),
    MEMORY_ALLOCATE_FAILED("4", "Memory Allocate Failed "),
    TPTYPES_EXECUTE_FAILED("5", "tptypes() execute failed "),
    CALL_TPINIT_FAILED("6", "待完错误描述"),
    CALL_TPCALL_FAILED("7", "待完错误描述"),
    MALLOC_ERROR_STR("100000", "分配缓冲区出错"),
    INVALID_PARAMETER_STR("100001", "无效的参数 "),
    INVALID_PARAMETER("100001", "无效的参数 "),
    DATA_FORMAT(" YYYYMMDD", "日期格式 "),
    DATA_TIME_FORMAT(" YYYYYMMDDHH24MISS", "日期时间格式 "),
    SYS_ERR_CODE("-1", "捕获到c++的exception"),
    OTHER_ERR_CODE("-2", "其他exception"),
    SELECT_ERR_MSG_ERROR("100", "根据出错代码取出错信息时执行SQL出错 "),
    FETCH_ERR_MSG_ERROR("101", "根据出错代码取出错信息时L出错"),
    INVALID_FIXED_DUE_ADJUST_TYPE_VALUE("102", "fixed due adjust type with negative adjust value  "),
    DB_CONNECT_UNKONW_EXP("-17", "连接数据库时发生未知异常"),
    GET_DBLINK_FAIL("-16", "获取数据库连接失败"),
    ROUTE_LOCATION_FAILED("-15", "数据路由定位失败"),
    ROUTE_MODULE_INIT_FAILED("-14", "数据路由模块初始化失败"),
    CONNET_DB_FAILED("-19", "连接数据库失败"),
    UNKNOW_EXCEPTION("-1", "未知异常"),
    ABM_TIMEOUT_NOERROR_STRING("-999", "OCS放行状态"),
    LOOK_FOR_STAFFID_FAIL("-20", "查找工号失败"),
    STAFF_ID_NOT_EXSITS("-18", "工号不存在"),
    PREPARE_RL_DIS_DATA_FAILED("-1", "准备失效调整批次数据失败"),
    PREPARE_RL_EXCD_DATA_FAILED("-1", "准备逾期调整批次数据失败"),
    QUERY_RLDIS_OWE_STATE_FAILED("-1", "查询当前红名单欠费状态失败"),
    NO_ACCT_IN_RL("-1", "未在红名单中发现账户信息"),
    GET_BILLCYCLYID_FAILED("-1", "获取当前账期失败"),
    DEAL_BATCH_DATAFAILED("-1", "批次数据处理失败"),
    NO_OFFSETBILLING_IN_ACCT_CREDIT("-1", "在ACCT_CREDIT表中找不到账户的交费期"),
    UPDATE_RLBT_STATE_FAILED("-1", "更新红黑名单状态失败"),
    FETCH_OFFSETBILLING_FAILED("-1", "获取账户缴费期失败"),
    QUERY_RLEXC_OWE_STATE_FAILED("-1", "查询当前红名单欠费状态失败"),
    UPDATE_RL_STATE_FAILED("-1", "更新红名单状态时错误"),
    ACCT_INFO_LOCK_FAILED("-1", "账户已经被锁，锁定账户失败"),
    FETCH_PAYMENT_METHOD_ERROR("203", "获取付款方式出错 "),
    ACCT_NOT_HAVE_ANY_PLAN("204", "帐户没有相应的付款方式 "),
    UPDATE_ACCT_BALANCE_VECTOR_EMPTY("305", "更新余额帐本输入为空 "),
    ACCT_BALANCE_NOT_MATCH("306", "余额帐本信息不匹配 "),
    FETCH_ACCT_BALANCE_ID_ERROR("308", "获取余额帐本序列值出错 "),
    TOO_MANY_ACCT_BALANCE("309", "符合条件的余额帐本多于一条 "),
    ACCT_BALANCE_NOT_FOUND("310", "余额帐本不存在 "),
    INVALID_ACCT_BALANCE_QUERY_KEY_VALUE("311", "无效的余额帐本查询键值 "),
    VALID_ACCT_BALANCE_FEEBILL_EMPTY("312", "获取有效帐户余额时，传入的欠费信息为空 "),
    INSERT_ACCT_BALANCE_BALANCE_ID_EMPTY("314", "插入余额帐本时,余额帐本标识为空 "),
    INSERT_ACCT_BALANCE_TYPE_ID_EMPTY("315", "插入余额帐本时,余额类型为空 "),
    INSERT_ACCT_BALANCE_BALANCE_EMPTY("316", "插入余额帐本时,余额为空 "),
    INSERT_ACCT_BALANCE_STATE_EMPTY("317", "插入余额帐本时,状态为空 "),
    INSERT_ACCT_BALANCE_STATE_DATE_EMPTY("318", "插入余额帐本时,状态变更日期为空 "),
    INSERT_ACCT_BALANCE_ACCT_ID_EMPTY("319", "插入余额帐本时,帐户标识为空 "),
    GET_ACCT_BALALNCE_ACCT_EMPTY("320", "查询余额帐本时,帐户标识为空 "),
    UPDATE_ACCT_BALANCE_BALANCE_EMPTY("321", "更新余额帐本时,余额为空 "),
    UPDATE_ACCT_BALANCE_STATE_EMPTY("322", "更新余额帐本时,状态为空 "),
    UPDATE_ACCT_BALANCE_ID_EMPTY("323", "更新余额帐本时,余额帐本标识为空 "),
    BALANCE_TYPE_ID_NOT_EXIST("325", "余额类型不存在 "),
    LOCK_ACCT_ITEM_FALIED("326", "按帐户标识对欠费记录加锁时失败 "),
    INSERT_ACCT_BALANCE_OBJECT_TYPE_ID_EMPTY("327", "327"),
    FLAG_EMPTY("410", "410"),
    STAFF_ID_EMPTY("411", "411"),
    SERV_ID_EMPTY("412", "412"),
    INSERT_PAYMENT_VECTOR_EMPTY("502", "插入付款流水输入为空 "),
    DELETE_PAYMENT_VECTOR_EMPTY("504", "删除付款流水输入为空 "),
    UPDATE_PAYMENT_VECTOR_EMPTY("506", "更新付款流水输入为空 "),
    INVALID_PAYMENT_QUERY_FLAG("508", "无效的付款流水查询标志 "),
    FETCH_PAYMENT_ID_ERROR("510", "获取付款流水序列值出错 "),
    PAYMENT_QUERY_FLAG_EMPTY("511", "付款流水查询标志为空 "),
    PAYMENT_QUERY_VALUE_EMPTY("512", "付款流水查询值为空 "),
    INVALID_PAYMENT_QUERY_VALUE("513", "无效的付款流水查询值 "),
    PAYMENT_QUERY_EMPTY("514", "查询付款信息时,传入的付款信息查询类为空 "),
    INSERT_PAYMENT_PAYMENT_ID_EMPTY("515", "插入付款记录表时,付款流水号为空 "),
    INSERT_PAYMENT_PAYMENT_METHOD_EMPTY("516", "插入付款记录表时,付款方式为空 "),
    INSERT_PAYMENT_PAYED_METHOD_EMPTY("517", "插入付款记录表时,实际付款方式为空 "),
    INSERT_PAYMENT_OPER_TYPE_EMPTY("518", "插入付款记录表时,操作类型为空 "),
    INSERT_PAYMENT_AMOUNT_EMPTY("519", "插入付款记录表时,实收金额为空 "),
    INSERT_PAYMENT_PAYMENT_DATE_EMPTY("520", "插入付款记录表时,付款日期为空 "),
    INSERT_PAYMENT_STATE_EMPTY("521", "插入付款记录表时,状态为空 "),
    INSERT_PAYMENT_STATE_DATE_EMPTY("522", "插入付款记录表时,状态变更日期为空 "),
    INSERT_PAYMENT_CREATED_DATE_EMPTY("523", "插入付款记录表时,记录生成日期为空 "),
    INSERT_PAYMENT_STAFF_ID_EMPTY("524", "插入付款记录表时,工号为空 "),
    DELETE_PAYMENT_PAYMENT_ID_EMPTY("525", "删除付款记录时,付款流水号为空 "),
    UPDATE_PAYMENT_PAYMENT_ID_EMPTY("526", "更新付款记录时,付款流水号为空 "),
    UPDATE_PAYMENT_STATE_EMPTY("527", "更新付款记录时,状态为空 "),
    UPDATE_PAYMENT_STATE_DATE_EMPTY("528", "更新付款记录时,状态变更日期为空 "),
    PAYMENT_METHOD_GROUP_EMPTY("529", "插入付款方式组时，付款方式组结构为空 "),
    INSERT_PAY_METHOD_GROUP_ID_EMPTY("530", "插入付款方式组时，付款流水号为空 "),
    DCC_SERV_ID_IS_EMPTY("531", "按用户查，serv_id不能为空"),
    INSERT_PAY_METHOD_GROUP_METHOD_EMPTY("531", "插入付款方式组时，付款方式为空 "),
    INSERT_PAYMENT_METHOD_GROUP_AMOUNT_EMPTY("532", "插入付款方式组时，付款金额为空 "),
    INSERT_PAYMENT_METHOD_GROUP_STATE_EMPTY("533", "插入付款方式组时，状态为空 "),
    INSERT_PAYMENT_METHOD_GROUP_DATE_EMPTY("534", "插入付款方式组时，状态变更日期为空 "),
    DCC_ACCT_ID_NOT_EXIST("568", "账户信息不存在"),
    INSERT_BALANCE_SOURCE_VECTOR_EMPTY("600", "插入余额来源输入为空 "),
    DELETE_BALANCE_SOURCE_VECTOR_EMPTY("602", "删除余额来源输入为空 "),
    INVALID_BALANCE_SOURCE_DELETE_FLAG("603", "无效的余额来源删除标志 "),
    UPDATE_BALANCE_SOURCE_VECTOR_EMPTY("605", "更新余额来源输入为空 "),
    INVALID_BALANCE_SOURCE_UPDATE_FLAG("606", "无效的余额来源更新标志 "),
    INVALID_BALANCE_SOURCE_QUERY_FLAG("608", "无效的余额来源查询标志 "),
    SELECT_BALANCE_SOURCE_ERROR("609", " 查询余额来源出错 "),
    FETCH_BALANCE_SOURCE_ERROR("610", " 获取余额来源出错 "),
    SELECT_OPER_INCOME_ID_ERROR("611", " 查询余额来源序列出错 "),
    FETCH_OPER_INCOME_ID_ERROR("612", "获取余额来源序列值出错 "),
    BALANCE_SOURCE_QUERY_FLAG_EMPTY("613", "余额来源查询标志为空 "),
    BALANCE_SOURCE_QUERY_VALUE_EMPTY("614", "余额来源查询值为空 "),
    INVALID_BALANCE_SOURCE_QUERY_VALUE("615", "无效的余额来源查询值 "),
    BALANCE_SOURCE_NOT_FOUND("616", "没有找到有效的余额来源记录 "),
    BALANCE_SOURCE_QUERY_EMPTY("617", "查询余额来源记录时,传入的余额来源查询结构为空 "),
    INSERT_BALANCE_SOURCE_INCOME_ID_EMPTY("618", "插入余额来源表时,余额来源标识为空 "),
    INSERT_BALANCE_SOURCE_BALANCE_ID_EMPTY("619", "插入余额来源表时,余额帐本标识为空 "),
    INSERT_BALANCE_SOURCE_OPER_TYPE_EMPTY("620", "插入余额来源表时,操作类型为空 "),
    INSERT_BALANCE_SOURCE_STAFF_ID_EMPTY("621", "插入余额来源表时,操作工号为空 "),
    INSERT_BALANCE_SOURCE_OPER_DATE_EMPTY("622", "插入余额来源表时,操作日期为空 "),
    INSERT_BALANCE_SOURCE_AMOUNT_EMPTY("623", "插入余额来源表时,金额为空 "),
    INSERT_BALANCE_SOURCE_SOURCE_TYPE_EMPTY("624", "插入余额来源表时,来源类型为空 "),
    INSERT_BALANCE_SOURCE_SOURCE_DESC_EMPTY("625", "插入余额来源表时,来源描述为空 "),
    INSERT_BALANCE_SOURCE_STATE_EMPTY("626", "插入余额来源表时,状态为空 "),
    INSERT_BALANCE_SOURCE_STATE_DATE_EMPTY("627", "插入余额来源表时,状态变更日期为空 "),
    INSERT_BALANCE_SOURCE_INV_OFFER_EMPTY("628", "插入余额来源表时,发票提供标识为空 "),
    INSERT_BALANCE_SOURCE_ALLOW_DRAW_EMPTY("629", "插入余额来源表时,允许提取标识为空 "),
    INSERT_BALANCE_SOURCE_PAYMENT_ID_EMPTY("630", "插入余额来源表时,付款流水号为空 "),
    INSERT_BALANCE_SOURCE_BALANCE_EMPTY("631", "插入余额来源表时,余额为空 "),
    DELETE_BALANCE_SOURCE_INCOME_ID_EMPTY("632", "删除余额来源记录时,余额来源标识为空 "),
    DELETE_BALANCE_SOURCE_PAYMENT_ID_EMPTY("633", "删除余额来源记录时,付款流水号为空 "),
    UPDATE_BALANCE_SOURCE_BALANCE_EMPTY("634", "更新余额来源记录时,余额为空 "),
    UPDATE_BALANCE_SOURCE_INCOME_ID_EMPTY("635", "更新余额来源记录时,余额来源标识为空 "),
    UPDATE_BALANCE_SOURCE_STATE_EMPTY("636", "更新余额来源记录时,状态为空 "),
    UPDATE_BALANCE_SOURCE_PAYMENT_ID_EMPTY("637", "更新余额来源记录时,付款流水号为空 "),
    UPDATE_BALANCE_SOURCE_STATE_DATE_EMPTY("638", "更新余额来源记录时,状态变更日期为空 "),
    BALANCE_PAYOUT_QUERY_STATE_EMPTY("700", "余额支出查询时，输入状态为空 "),
    INVALID_BALANCE_PAYOUT_QUERY_FLAG("701", "无效的余额支出查询标志 "),
    INSERT_BALANCE_PAYOUT_VECTOR_EMPTY("704", "插入余额支出时，输入为空 "),
    DELETE_BALANCE_PAYOUT_VECTOR_EMPTY("706", "删除余额支出时，输入为空 "),
    INVALID_BALANCE_PAYOUT_DELETE_FLAG("707", "无效的余额支出删除标志 "),
    UPDATE_BALANCE_PAYOUT_VECTOR_EMPTY("709", "更新余额支出时，输入为空 "),
    INVALID_BALANCE_PAYOUT_UPDATE_FLAG("710", "无效的余额支出更新标志 "),
    FETCH_OPER_PAYOUT_ID_ERROR("713", "获取余额支出序列值出错 "),
    BALANCE_PAYOUT_QUERY_FLAG_EMPTY("714", "余额支出查询标志为空 "),
    BALANCE_PAYOUT_QUERY_VALUE_EMPTY("715", "余额支出查询值为空 "),
    INSERT_BALANCE_PAYOUT_ID_EMPTY("716", "插入余额支出表,余额支出标识为空 "),
    INSERT_BALANCE_PAYOUT_BALANCE_ID_EMPTY("717", "插入余额支出表,余额帐本标识为空 "),
    INSERT_BALANCE_PAYOUT_OPER_TYPE_EMPTY("718", "插入余额支出表,操作类型为空 "),
    INSERT_BALANCE_PAYOUT_STAFF_EMPTY("719", "插入余额支出表,工号为空 "),
    INSERT_BALANCE_PAYOUT_OPER_DATE_EMPTY("720", "插入余额支出表,操作日期为空 "),
    INSERT_BALANCE_PAYOUT_AMOUNT_EMPTY("721", "插入余额支出表,金额为空 "),
    INSERT_BALANCE_PAYOUT_BALANCE_EMPTY("722", "插入余额支出表,余额为空 "),
    INSERT_BALANCE_PAYOUT_PRINTNUM_EMPTY("723", "插入余额支出表,打印次数为空 "),
    INSERT_BALANCE_PAYOUT_STATE_EMPTY("724", "插入余额支出表,状态为空 "),
    INSERT_BALANCE_PAYOUT_STATE_DATE_EMPTY("725", "插入余额支出表,状态变更日期为空 "),
    DELETE_BALANCE_PAYOUT_ID_EMPTY("726", "删除余额支出表,余额支出标识为空 "),
    DELETE_BALANCE_PAYOUT_BALANCE_EMPTY("727", "删除余额支出表,余额帐本标识为空 "),
    DELETE_BALANCE_PAYOUT_BILL_EMPTY("728", "删除余额支出表,销帐流水号为空 "),
    UPDATE_BALANCE_PAYOUT_ID_EMPTY("729", "更新余额支出表,余额支出标识为空 "),
    UPDATE_BALANCE_PAYOUT_BALANCE_EMPTY("730", "更新余额支出表,余额帐本标识为空 "),
    UPDATE_BALANCE_PAYOUT_BILL_EMPTY("731", "更新余额支出表,销帐流水号为空 "),
    BALANCE_PAYOUT_QUERY_EMPTY("732", "查询余额支出记录,传入的余额查询结构为空 "),
    BALANCE_MONTH_PAYOUT_QUERY_ERROR("733", "月结电子发票查询余额支出失败 "),
    BALANCE_MONTH_BILLID_QUERY_ERROR("734", "月结电子发票查询销账流水失败 "),
    BALANCE_MONTH_ALIPAY_QUERY_ERROR("735", "月结电子发票查询支付宝红包失败 "),
    BALANCE_MONTH_ACCT_CUST_QUERY_ERROR("736", "月结电子发票查询付费客户失败 "),
    BALANCE_MONTH_TAXPAYER_QUERY_ERROR("737", "月结电子发票查询纳税人识别号失败 "),
    QUERY_BILL_STATE_EMPTY("800", "查询销帐流水时，输入状态为空 "),
    INVALID_BILL_QUERY_FLAG("801", "无效的销帐流水查询标志 "),
    INSERT_BILL_VECTOR_EMPTY("804", "插入销帐流水表时，输入参数为空 "),
    DELETE_BILL_VECTOR_EMPTY("806", "删除销帐流水表时，输入参数为空 "),
    INVALID_DELETE_BILL_FLAG("807", "无效的销帐流水删除标志 "),
    UPDATE_BILL_VECTOR_EMPTY("809", "更新销帐流水时，输入参数为空 "),
    INVALID_UPDATE_BILL_FLAG("810", "无效的销帐流水更新标志 "),
    FETCH_BILL_ID_ERROR("813", "获取销帐流水序列值出错 "),
    BILL_QUERY_FLAG_EMPTY("814", "销帐流水查询标志为空 "),
    BILL_QUERY_VALUE_EMPTY("815", "销帐流水查询值为空 "),
    NOT_HAVE_ANY_INVALID_BILL_ID("817", "不存在任何销帐流水 "),
    QUERY_BAL_INOUT_RELA_STATE_EMPTY("900", "查询余额来源支出关系表时，输入状态为空 "),
    INVALID_QUERY_BAL_INOUT_RELA_FLAG("901", "无效的余额来源支出关系表查询标志 "),
    INSERT_BAL_INOUT_RELA_VECTOR_EMPTY("904", "插入余额来源支出关系表时，输入参数为空  "),
    DELETE_BAL_INOUT_RELA_VECTOR_EMPTY("906", "删除余额来源支出关系表时，输入参数为空 "),
    INVALID_DELETE_BAL_INOUT_RELA_FLAG("907", "无效的余额来源支出关系表查询标志 "),
    UPDATE_BAL_INOUT_RELA_VECTOR_EMPTY("909", "更新余额来源支出关系表时，输入参数为空 "),
    INVALID_BAL_INOUT_RELA_UPDATE_FLAG("910", "无效的余额来源支出关系表查询标志 "),
    FETCH_BALANCE_RELA_ID_ERROR("913", "获取余额来源支出关系序列值出错 "),
    BAL_INOUT_RELA_QUERY_FLAG_EMPTY("914", "余额来源支出关系查询标志为空 "),
    BAL_INOUT_RELA_QUERY_VALUE_EMPTY("915", "余额来源支出关系查询值为空 "),
    INVALID_BAL_INOUT_RELA_QUERY_VALUE("916", "无效的余额来源支出关系查询值 "),
    BALANCE_INOUT_RELA_QUERY_EMPTY("917", "查询余额来源支出关系表时,传入的查询结构为空 "),
    INSERT_BAL_INOUT_RELA_ID_EMPTY("918", "插入余额来源支出关系表时,余额来源支出关系标识为空 "),
    INSERT_BAL_INOUT_RELA_INCOME_ID_EMPTY("919", "插入余额来源支出关系表时,余额来源标识为空 "),
    INSERT_BAL_INOUT_RELA_PAYOUT_ID_EMPTY("920", "插入余额来源支出关系表时,余额支出标识为空 "),
    INSERT_BAL_INOUT_RELA_BALANCE_ID_EMPTY("921", "插入余额来源支出关系表时,余额帐本标识为空 "),
    INSERT_BAL_INOUT_RELA_PRE_AMOUNT_EMPTY("922", "插入余额来源支出关系表时,支出前余额为空 "),
    INSERT_BAL_INOUT_RELA_PAY_AMOUNT_EMPTY("923", "插入余额来源支出关系表时,支出金额为空 "),
    INSERT_BAL_INOUT_RELA_STATE_EMPTY("924", "插入余额来源支出关系表时,状态为空 "),
    INSERT_BAL_INOUT_RELA_STATE_DATE_EMPTY("925", "插入余额来源支出关系表时,状态变更日期为空 "),
    DELETE_BAL_INOUT_RELA_ID_EMPTY("926", "删除余额来源支出关系表时,余额来源支出关系标识为空 "),
    DELETE_BAL_INOUT_RELA_INCOME_ID_EMPTY("927", "删除余额来源支出关系表时,余额来源标识为空 "),
    DELETE_BAL_INOUT_RELA_PAYOUT_ID_EMPTY("928", "删除余额来源支出关系表时,余额支出标识为空 "),
    UPDATE_BAL_INOUT_RELA_ID_EMPTY("929", "更新余额来源支出关系表时,余额来源支出关系标识为空 "),
    UPDATE_BAL_INOUT_RELA_PAYOUT_ID_EMPTY("930", "更新余额来源支出关系表时,余额支出标识为空 "),
    ACCT_ERROR_UPDATE("1002", "修改帐户信息出错"),
    NOT_QUERY_ACCT_INFO_FLAG("1003", "没有提供帐户查询标志 "),
    TOO_MANY_SERV_INFO("1007", "存在多条符合条件的用户信息 "),
    SERV_INFO_QUERY_FLAG_EMPTY("1008", "用户信息查询标志为空 "),
    SERV_INFO_QUERY_VALUE_EMPTY("1009", "用户信息查询时查询条件值为空 "),
    SERV_INFO_QUERY_SUBJOIN_VALUE_EMPTY("1010", "用户信息查询时附加查询条件值为空 "),
    INVALID_SERV_QUERY_FLAG("1011", "无效的用户信息查询标志 "),
    FETCH_ACCT_DEPUTY_ERROR("1013", "获取帐户代表号码信息出错 "),
    INVALID_ACCT_QUERY_FLAG("1014", "无效的帐户信息查询标志 "),
    SERV_OR_ACCT_NOT_FOUND("1015", "找不到用户或帐户档案 "),
    SERV_INFO_QUERY_NULL("1016", "用户信息查询时,传入的查询结构为空 "),
    QUERY_ACCT_INFO_VALUE_EMPTY("1017", "查询帐户信息时，查询条件值为空 "),
    INVLID_QUERY_VALUE4("1018", "按号码查询帐户信息时，所对应的查询标志不存在 "),
    UPDATE_ACCT_ITEM_AGGR_ERROR("1026", "1026"),
    NOT_ENABLE_EXEC_RT_VIREMENT("1031", "1031"),
    RT_BILLING_CYCLE_NOT_EXIST("1032", "1032"),
    REGION_AUTH_INIT_PARAMETER_FIRST("1033", "1033"),
    ERR_TABLE_FORMAT_NO_DATA("1901", "1901"),
    ERR_CELL_INFO_NO_DATA("1902", "1902"),
    ERR_FONT_INFO_NO_DATA("1903", "1903"),
    ERR_CELL_NUMBER("1904", "1904"),
    ERR_GET_ACCT_INFO("1905", "1905"),
    ERR_GET_SALE_ID("1906", "1906"),
    ERR_GET_SERV_INFO("1907", "待完错误描述"),
    ACCT_INFO_NULL("1908", "待完错误描述"),
    SERV_INFO_NULL("1909", "待完错误描述"),
    ERR_GET_TEMP_DEFINE("1910", "待完错误描述"),
    ERR_GET_TEMP_BLOCK("1911", "待完错误描述"),
    ERR_GET_BLOCK_TABLE("1912", "待完错误描述"),
    ERR_GET_TABLE_CELL("1913", "待完错误描述"),
    ERR_GET_CELL_FORMAT("1914", "待完错误描述"),
    ERR_GET_TABLE_FORMAT("1915", "待完错误描述"),
    ERR_GET_FONT_INFO("1916", "待完错误描述"),
    ERR_GET_BLOCK_PIC("1917", "待完错误描述"),
    ERR_GET_BLOCK_HIS("1918", "待完错误描述"),
    ERR_GET_CUST_BILL("1919", "待完错误描述"),
    ERR_COMBINE_CONTENT("1920", "待完错误描述"),
    ERR_BLOCK_TYPE("1921", "待完错误描述"),
    ERR_LOAD_CUST_BILL("1923", "待完错误描述"),
    ERR_NO_TEMPLATE("1924", "待完错误描述"),
    ERR_COLUMN_NUM("1925", "待完错误描述"),
    ERR_HEIGHT_NUM("1926", "待完错误描述"),
    ERR_SORT_NUM("1927", "待完错误描述"),
    ERR_CONFIG_INFO("1928", "待完错误描述"),
    ERR_BLOCK_WIDTH("1929", "待完错误描述"),
    ERR_COLUMN_WIDTH("1930", "待完错误描述"),
    ERR_ROWGROUP_NUM("1931", "待完错误描述"),
    ERR_ROWCOL_NUM("1932", "待完错误描述"),
    ERR_ROWCOL_ID("1933", "待完错误描述"),
    ERR_GET_SWITCH_VALUE("1934", "待完错误描述"),
    ACCT_ITEM_ERROR_INSERT("2001", "插入滞纳金帐目出错"),
    ACCT_ITEM_ERROR_UPDATE("2002", "修改帐目表出错"),
    ACCT_ITEM_ERROR_DELETE("2003", "删除帐目出错"),
    QUERY_ACCT_ITEM_STAFF_ID_EMPTY("2006", "查询欠费帐目表时，工号为空 "),
    INVALID_ACCT_ITEM_QUERY_FLAG("2007", "无效的欠费帐目查询标志 "),
    SPECIFY_ACCT_ITEM_SELECT_ERROR("2008", "特定欠费帐目查询时出错 "),
    SPECIFY_ACCT_ITEM_FETCH_ERROR("2009", "获取特定欠费帐目记录时出错 "),
    NO_OWE_FEE("2010", "无欠费"),
    UPDATE_ACCT_ITEM_VECTOR_EMPTY("2011", "更新欠费帐目表时传入的参数为空 "),
    INSERT_ACCT_ITEM_VECTOR_EMPTY("2013", "插入欠费帐目表时传入的参数为空 "),
    FETCH_ACCT_ITEM_ID_ERROR("2016", "获取欠费帐目标识序列值出错 "),
    INVALID_GET_SUM_OWE_CHARGE_STATE_FLAG("2018", "查询总欠费信息出错 "),
    INVALID_ACCT_ITEM_UPDATE_STATE_FLAG("2020", "无效的欠费帐目更新标志 "),
    ACCT_QRY_FLAG_COND_EMPTY("2021", "根据帐户标识查询欠费时帐户标识为空 "),
    SERV_QRY_FLAG_COND_EMPTY("2022", "根据用户标识查询欠费时,用户标识为空 "),
    ACCT_SERV_QRY_FLAG_ACCT_EMPTY("2023", "根据帐户和用户标识查询欠费时,用户标识为空 "),
    ACCT_SERV_QRY_FLAG_SERV_EMPTY("2024", "根据帐户和用户标识查询欠费时,帐户标识为空 "),
    INSERT_ACCT_ITEM_ITEM_ID_EMPTY("2025", "插入欠费帐目表时,帐目标识为空 "),
    INSERT_ACCT_ITEM_SOURCE_ID_EMPTY("2026", "插入欠费帐目表时,帐目来源类型为空 "),
    INSERT_ACCT_ITEM_ITEM_TYPE_ID_EMPTY("2027", "插入欠费帐目表时,帐目类型为空 "),
    INSERT_ACCT_ITEM_CYCLE_ID_EMPTY("2028", "插入欠费帐目表时,帐务周期为空 "),
    INSERT_ACCT_ITEM_ACCT_ID_EMPTY("2029", "插入欠费帐目表时,帐户标识为空 "),
    INSERT_ACCT_ITEM_SERV_ID_EMPTY("2030", "插入欠费帐目表时,用户标识为空 "),
    INSERT_ACCT_ITEM_AMOUNT_EMPTY("2031", "插入欠费帐目表时,金额为空 "),
    INSERT_ACCT_ITEM_CREATED_DATE_EMPTY("2032", "插入欠费帐目表时,记录生成日期为空 "),
    INSERT_ACCT_ITEM_PAYMENT_METHOD_EMPTY("2033", "插入欠费帐目表时,付款方式为空 "),
    INSERT_ACCT_ITEM_STATE_EMPTY("2034", "插入欠费帐目表时,状态为空 "),
    INSERT_ACCT_ITEM_STATE_DATE_EMPTY("2035", "插入欠费帐目表时,状态变更日期为空 "),
    INSERT_ACCT_ITEM_INVOICE_OFFER_EMPTY("2036", "插入欠费帐目表时,发票提供标识为空 "),
    UPDATE_ACCT_ITEM_CYCLE_EMPTY("2037", "更新欠费帐目表时,帐务周期标识为空 "),
    UPDATE_ACCT_ITEM_SERV_ID_EMPTY("2038", "更新欠费帐目表时,用户标识为空 "),
    UPDATE_ACCT_ITEM_ITEM_TYPE_EMPTY("2039", "更新欠费帐目表时,帐目类型标识为空 "),
    UPDATE_ACCT_ITEM_ACCT_ID_EMPTY("2040", "更新欠费帐目表时,帐户标识为空 "),
    UPDATE_ACCT_ITEM_STATE_EMPTY("2041", "更新欠费帐目表时,状态为空 "),
    UPDATE_ACCT_ITEM_STATE_DATE_EMPTY("2042", "更新欠费帐目表时,状态变更日期为空 "),
    FEE_BILL_QUERY_EMPTY("2043", "欠费信息查询时,传入的查询结构为空 "),
    QUERY_ACCT_ITEM_DUE_FEE_EMPTY("2044", "根据欠费记录，获取相应的滞纳金记录结构时出错 "),
    QUERY_ACCT_ITEM_DUE_ACCT_ID_EMPTY("2045", "获取滞纳金记录结构时，帐户标识为空 "),
    QUERY_ACCT_ITEM_DUE_LEVEL_INVALID("2046", "获取滞纳金记录结构时，预存级别为空 "),
    QUERY_ACCT_ITEM_DUE_SERV_ID_EMPTY("2047", "获取滞纳金记录结构时，用户标识为空 "),
    QUERY_ACCT_ITEM_DUE_TYPE_ID_EMPTY("2048", "获取滞纳金记录结构时，帐目类型为空 "),
    FEEBILL_QUERY_STAFF_ID_EMPTY("2051", "查询欠费信息时，传入的工号为空 "),
    FEEBILL_QUERY_ACCT_ID_EMPTY("2052", "查询欠费信息时，传入的帐户标识为空 "),
    GET_VAL_BALANCE_GET_FLAG_EMPTY("2053", "获取可用余额时，传入的欠费组织结构标识为空 "),
    GET_VAL_BALANCE_STAFF_ID_EMPTY("2054", "获取可用作客时，传入的工号为空 "),
    QUERY_ACCT_ITEM_DUE_CYCLE_EMPTY("2055", "销帐查询欠费信息时，传入的帐务周期数据为空 "),
    QUERY_ACCT_ITEM_DUE_CYCLE_NULL("2056", "销帐查询欠费信息时，帐务周期标识为空 "),
    FEEBILLDETAIL_STAFF_ID_EMPTY("2057", "查询欠费明细信息时，未传入工号标识 "),
    FEEBILLDETAIL_ACCT_ID_EMPTY("2058", "查询欠费明细信息时，未传入帐户标识 "),
    FEEBILLDETAIL_QUERY_FLAG_EMPTY("2059", "查询欠费明细信息时，未传入查询标志 "),
    FEEBILLDETAIL_BILLING_CYCLE_EMPTY("2060", "查询欠费明细信息时，未传入帐务周期标识 "),
    FEEBILLDETAIL_GET_FLAG_EMPTY("2061", "查询欠费明细信息时，未传入数据组织标志 "),
    FEEBILLDETAIL_QUERY_FLAG_MISMATCH("2062", "查询欠费明细信息时，传入按用户查询的标识，但用户标识为空 "),
    MERGE_ACCT_ITEM_SOURCE_DATE_EMPTY("2063", "归并欠费信息时，传入的源欠费数据为空 "),
    MERGE_ACCT_ITEM_ACCT_ID_NULL("2064", "归并欠费信息时，源欠费数据中帐户标识为空 "),
    MERGE_ACCT_ITEM_ACCT_ID_MISMATCH("2065", "归并欠费信息时，源欠费数据中，存在多个帐户标识 "),
    MERGE_ACCT_ITEM_BILLING_CYCLE_EMPTY("2066", "归并欠费信息时，源欠费数据中，未包含帐务周期信息 "),
    MERGE_ACCT_ITEM_BILLING_CYCLE_NULL("2067", "归并欠费信息时，源欠费数据中，帐务周期标识为空 "),
    MERGE_ACCT_ITEM_SERV_ID_NULL("2068", "归并欠费信息时，源欠费数据中，用户标识为空 "),
    MERGE_ACCT_ITEM_TYPE_ID_NULL("2069", "归并欠费信息时，源欠费数据中，帐目类型为空 "),
    INVALID_MERGE_ACCT_ITEM_FLAG("2070", "归并欠费信息时，传入的归并类型无法识别 "),
    INVALID_BILL_FORMAT_ID("2072", "无法识别的发票格式 "),
    ACCT_ITEM_TYPE_NOT_MERGE("2073", "警告：某一帐目类型未归并到相应帐单项的，请检查 "),
    ORDER_ACCT_ITEM_SERV_ID_NULL("2074", "按用户排序时，用户标识为空 "),
    ORDER_ACCT_ITEM_CYCLE_EMPTY("2075", "按帐务周期排序时，帐务周期标识为空 "),
    ORDER_ACCT_ITEM_TYPE_ID_NULL("2076", "按帐目类型排序时，帐目类型为空 "),
    DUPLICATE_FEE_BILL_NULL("2077", "复制T_FEEBILL结构时，源结构为空 "),
    BALANCE_TRANSFER_SOURCE_EMPTY("2080", "余额转帐时，转出的余额帐本标识为空 "),
    BALANCE_TRANSFER_BALANCE_NULL("2081", "余额转帐时，转出金额为空 "),
    BALANCE_TRANSFER_BALANCE_INVALID("2082", "余额转帐时，转出金额小于等于0 "),
    BALANCE_TRANSFER_DEST_ACCT_NULL("2083", "余额转帐时，目标帐户标识为空 "),
    BALANCE_TRANSFER_STAFF_ID_NULL("2084", "余额转帐时，操作员工标识为空 "),
    BALANCE_TRANSFER_BALANCE_MISMATCH("2085", "余额转帐时，需要转出的总金额与余额帐本上的余额之和不相等 "),
    BALANCE_TRANSFER_INPUT_EMPTY("2086", "余额转帐时，传入的转帐申请信息结构为空 "),
    INVALID_INVOICE_INFO_QRY_FLAG("2087", "无效的发票信息查询标志 "),
    BILL_HISTORY_QUERY_FLAG_NULL("2090", "查询历史缴费信息时，查询标志为空 "),
    BILL_HISTORY_QUERY_VALUE_NULL("2091", "查询历史缴费信息时，查询条件值为空 "),
    BILL_HISTORY_NOT_HAVE_DATA("2092", "未查询到符合条件的历史缴费信息 "),
    GET_VAL_BALANCE_PRE_CHANGE_EMPTY("2093", "选销时，查询可用余额未传入上次零头 "),
    REVERSE_PAYMENT_MONEY_MODIFIED("2094", "冲正时，付款金额已经发生变化 "),
    GET_DUE_RATE_INFO_FAILED("2096", "获取违约金费率出错 "),
    ACCT_BALANCE_SOURCE_MONEY_MISMATCH("2097", "余额帐本金额与来源明细不符 "),
    GET_BALANCE_INFO_ACCT_MISMATCH("3000", "查询余额帐本信息时，帐户标识不匹配 "),
    JUDGE_CONDITION_EMPTY("3002", "获取判断条件信息时,传入的JudgeCondition为空 "),
    DEPOSIT_INFO_VECTOR_EMPTY("3003", "预存时,传入的预存信息为空 "),
    CASH_BILL_FEE_BILL_CHARGE_EMPTY("3004", "销帐时,欠费结构信息为空 "),
    GET_VAL_BALANCE_FEE_BILL_EMPTY("3005", "获取可用余额时,传入的欠费信息为空 "),
    GET_VAL_BALANCE_BILLING_CYCLE_EMPTY("3006", "获取可用余额时,欠费信息中的帐务周期标识为空 "),
    GET_VAL_BALANCE_CYCLE_VECTOR_EMPTY("3007", "获取可用余额时,欠费信息中的帐务周期结构为空 "),
    FEE_BILL_ACCT_ID_EMPTY("3008", "欠费信息结构中,帐户标识为空 "),
    FEE_BILL_CHARGE_EMPTY("3009", "欠费信息结构中,欠费金额为空 "),
    JUDGE_ACCT_LEVEL_BALANCE_EMPTY("3010", "判断帐户级能否自动销帐时, 余额帐本结构为空 "),
    JUDGE_ACCT_LEVEL_FEE_EMPTY("3011", "判断帐户级能否自动销帐时, 欠费信息结构为空 "),
    JUDGE_ACCT_LEVEL_CYCLE_VECTOR_EMPTY("3012", "判断帐户级能否自动销帐时, 欠费信息结构中,帐务周期结构为空 "),
    JUDGE_ACCT_LEVEL_BILLING_CYCLE_EMPTY("3013", "判断帐户级能否自动销帐时, 欠费信息结构中,帐务周期结构下的帐务周期标识为空 "),
    JUDGE_ACCT_LEVEL_CHARGE_EMPTY("3014", "判断帐户级能否自动销帐时, 欠费信息结构中,欠费金额为空 "),
    JUDGE_ACCT_LEVEL_DUE_EMPTY("3015", "判断帐户级能否自动销帐时, 欠费信息结构中,滞纳金为空 "),
    JUDGE_ACCT_LEVEL_BILLED_CHARGE_EMPTY("3016", "判断帐户级能否自动销帐时, 欠费信息结构中,已抵扣金额为空 "),
    JUDGE_SERV_LEVEL_BALANCE_EMPTY("3017", "判断用户级能否自动销帐时, 余额帐本结构为空 "),
    JUDGE_SERV_LEVEL_FEEBILL_EMPTY("3018", "判断用户级能否自动销帐时, 欠费信息结构为空 "),
    JUDGE_SERV_LEVEL_BAL_SERV_ID_EMPTY("3019", "判断用户级能否自动销帐时, 余额帐本结构中,用户标识为空 "),
    JUDGE_SERV_LEVEL_FEE_SERV_ID_EMPTY("3020", "判断用户级能否自动销帐时, 欠费信息结构中,用户标识为空 "),
    JUDGE_SERV_LEVEL_CYCLE_VECTOR_EMPTY("3021", "判断用户级能否自动销帐时, 欠费信息结构中,帐务周期结构为空 "),
    JUDGE_SERV_LEVEL_BILLING_CYCLE_EMPTY("3022", "判断用户级能否自动销帐时, 欠费信息结构中,帐务周期结构下的帐务周期标识为空 "),
    JUDGE_SERV_LEVEL_CHARGE_EMPTY("3023", "判断用户级能否自动销帐时, 欠费信息结构中,欠费金额为空 "),
    JUDGE_SERV_LEVEL_DUE_EMPTY("3024", "判断用户级能否自动销帐时, 欠费信息结构中,滞纳金为空 "),
    JUDGE_SERV_LEVEL_BILLED_CHARGE_EMPTY("3025", "判断用户级能否自动销帐时, 欠费信息结构中,已抵扣金额为空 "),
    JUDGE_ITEM_LEVEL_BALANCE_EMPTY("3026", "判断用户帐目组级能否自动销帐时, 余额帐本结构为空 "),
    JUDGE_ITEM_LEVEL_FEEBILL_EMPTY("3027", "判断用户帐目组级能否自动销帐时, 欠费信息结构为空 "),
    JUDGE_ITEM_LEVEL_BAL_SERV_ID_EMPTY("3028", "判断用户帐目组级能否自动销帐时, 余额帐本结构中,用户标识为空 "),
    JUDGE_ITEM_LEVEL_FEE_SERV_ID_EMPTY("3029", "判断用户帐目组级能否自动销帐时, 欠费信息结构中,用户标识为空 "),
    JUDGE_ITEM_LEVEL_ITEM_TYPE_EMPTY("3030", "判断用户帐目组级能否自动销帐时, 欠费信息结构中,帐目标识为空 "),
    JUDGE_ITEM_LEVEL_CYCLE_VECTOR_EMPTY("3031", "判断用户帐目组级能否自动销帐时, 欠费信息结构中,帐务周期结构为空 "),
    JUDGE_ITEM_LEVEL_BILLING_CYCLE_EMPTY("3032", "判断用户帐目组级能否自动销帐时, 欠费信息结构中,帐务周期结构下的帐务周期标识为空 "),
    JUDGE_ITEM_LEVEL_CHARGE_EMPTY("3033", "判断用户帐目组级能否自动销帐时, 欠费信息结构中,欠费金额为空 "),
    JUDGE_ITEM_LEVEL_DUE_EMPTY("3034", "判断用户帐目组级能否自动销帐时, 欠费信息结构中,滞纳金为空 "),
    JUDGE_ITEM_LEVEL_BILLED_CHARGE_EMPTY("3035", "判断用户帐目组级能否自动销帐时, 欠费信息结构中,已抵扣金额为空 "),
    CASH_BILL_DUE_NOT_DUE_RECORD("3036", "销帐时，滞纳金金额大于零，但没有对应的明细记录 "),
    VALID_BALANCE_NOT_LEGALITY("3037", "自动销帐时，获取的可用余额大于欠费金额 "),
    DEPOSIT_PAYED_METHOD_EMPTY("3038", "预存时，未传入实际付款方式 "),
    BILL_STAFF_ID_EMPTY("4000", "销帐时传入工号为空 "),
    BILL_BILL_METHOD_EMPTY("4001", "销帐请示时，销帐类型为空 "),
    BILL_PAYMENT_METHOD_EMPTY("4002", "销帐时传入的付款方式为空 "),
    BILL_FEE_BILL_EMPTY("4003", "销帐时传入的欠费信息为空 "),
    ACCT_ID_MISMATCH("4004", "销帐时合同号不一致 "),
    CASH_BILL_FUNDS_LEVEL_EMPTY("4005", "销帐时传入的预在级别为空 "),
    CASH_BILL_CHARGE_EMPTY("4006", "销帐时未传入应收金额 "),
    CASH_BILL_AMOUNT_EMPTY("4007", "销帐时未传入实收金额 "),
    CHANGE_NOT_CONFIG("4008", "零头额度未配置 "),
    DEPOSIT_INFO_EMPTY("4009", "预存信息为空 "),
    DEPOSIT_OPERATOR_FLAG_EMPTY("4010", "预存类型为空 "),
    BALANCE_PAYOUT_SIMPAYOUTINFO_EMPTY("4011", "余额支出结构信息为空 "),
    BILL_ACCT_ID_EMPTY("4012", "帐户标识为空 "),
    INVALID_FUNDS_LEVEL("4013", "无效的预存级别信息 "),
    INVALID_CASH_BILL_METHOD("4014", "无效的销帐方式标识 "),
    BILL_AMOUNT_NOT_ENOUGH("4015", "实收金额不足销帐 "),
    CASH_BILL_EMPTY("4019", "销帐请求结构为空 "),
    BILL_SHOULD_MONEY_MISMATCH("4020", "应收金额不匹配 "),
    INVALID_CASH_BILL_BILL_METHOD("4021", "无效的销帐模式 "),
    BILL_QUERY_EMPTY("4023", "查询销帐记录信息进,传入的class BillQuery 为空 "),
    INSERT_BILL_BILL_ID_EMPTY("4024", "插入销帐记录表, 销帐流水号为空 "),
    INSERT_BILL_PAYMENT_METHOD_EMPTY("4025", "插入销帐记录表, 付款方式为空 "),
    INSERT_BILL_BILLING_CYCLE_ID_EMPTY("4026", "插入销帐记录表, 帐务周期标识为空 "),
    INSERT_BILL_ACCT_ID_EMPTY("4027", "插入销帐记录表, 帐户标识为空 "),
    INSERT_BILL_BILL_AMOUNT_EMPTY("4028", "插入销帐记录表, 销帐金额为空 "),
    INSERT_BILL_DUE_EMPTY("4029", "插入销帐记录表, 滞纳金为空 "),
    REFUND_INFO_EMPTY("4030", "退款请求信息为空 "),
    REFUND_ACCT_ID_EMPTY("4031", "退款时传入的帐户标识为空 "),
    REFUND_CHARGE_EMPTY("4032", "退款时退款金额为空 "),
    REFUND_CHARGE_NEGATIVE("4033", "退款时退款金额小于0 "),
    NOT_HAVE_VALID_ACCT_BALANCE("4034", "该帐户无有效的余额帐本 "),
    REFUND_STAFF_ID_EMPTY("4035", "退款时传入工号为空 "),
    REVERSE_INFO_EMPTY("4036", "反销帐结构信息为空 "),
    REVERSE_SERIAL_TYPE_EMPTY("4037", "反销帐流水类型为空 "),
    REVERSE_SERIAL_NBR_EMPTY("4038", "反销帐流水号为空 "),
    INVALID_SERIAL_TYPE("4039", "无效的反销帐流水类型 "),
    REVERSE_PAY_STAFF_EMPTY("4040", "冲正时工号为空 "),
    PAYMENT_RECORD_NOT_EXIST("4041", "付款记录不存在 "),
    PAYMENT_NOT_BALANCE_SOURCE("4042", "付款流水没有对应的余额来源记录 "),
    REVERSE_BILL_STAFF_ID_EMPTY("4043", "反销帐时工号为空 "),
    BILL_RECORD_NOT_EXIST("4044", "销帐记录不存在 "),
    BILL_RECORD_STATE_ERROR("4045", "销帐记录状态不正确 "),
    BILL_ID_NOT_PAYOUT("4046", "销帐流水没有对应余额支出记录 "),
    BALANCE_SOURCE_NOT_EXIST("4047", "余额来源记录不存在 "),
    CHANGE_RECORD_NOT_EXIST("4048", "余额帐本零头记录不存在 "),
    PAYMENT_RECORD_STATE_ERROR("4049", "付款记录状态不正确 "),
    BILL_CUR_CHANGE_MISMATCH("4050", "销帐时本次余额不匹配 "),
    DEPOSIT_OBJ_TYPE_VAL_BALANCE_MISMATCH("4051", "存款级别和可用余额不匹配 "),
    PAYOUT_NOT_INOUT_RELA("4053", "余额支出没有对应的余额来源支出关系记录 "),
    ACCT_BALANCE_ID_MISMATCH("4054", "余额来源表和余额来源支出关系表的余额帐本标识不匹配 "),
    BALANCE_FEE_MISMATCH("4055", "余额预存级别和欠费组合标识不匹配 "),
    BALANCE_BALANCE_DETAIL_MISMATCH("4056", "可用余额大于零，却无对应的可用余额明细信息 "),
    FETCH_ORG_ERROR("4060", "获取运维机构出错 "),
    FETCH_BSS_ORG_ERROR("4062", "获取运营机构出错 "),
    BSS_ORG_SWITCH_NOT_FOUND("4065", "指定的销帐参数没有配 "),
    SELECT_BSS_ORG_SWITCH_BSS_ORG_EMPTY("4066", "查询系统开关时，运营机构为空 "),
    INSERT_BILL_DERATE_DUE_EMPTY("4067", "插入销帐记录表, 减免滞纳金为空 "),
    INSERT_BILL_BALANCE_EMPTY("4068", "插入销帐记录表, 使用余额为空 "),
    INSERT_BILL_LAST_CHANGE_EMPTY("4069", "插入销帐记录表, 上次零头为空 "),
    INSERT_BILL_CUR_CHANGE_EMPTY("4070", "插入销帐记录表, 本次零头为空 "),
    INSERT_BILL_CREATED_DATE_EMPTY("4071", "插入销帐记录表, 记录生成日期为空 "),
    INSERT_BILL_PAYMENT_DATE_EMPTY("4072", "插入销帐记录表, 付款日期为空 "),
    INSERT_BILL_USED_DERATE_BAL_EMPTY("4073", "插入销帐记录表, 强制冲减金额为空 "),
    INSERT_BILL_STATE_EMPTY("4074", "插入销帐记录表, 状态为空 "),
    INSERT_BILL_STATE_DATE_EMPTY("4075", "插入销帐记录表, 状态变更日期为空 "),
    INSERT_BILL_STAFF_ID_EMPTY("4076", "插入销帐记录表, 操作员工号为空 "),
    DELETE_BILL_BILL_ID_EMPTY("4077", "删除销帐记录时, 销帐流水号为空 "),
    DELETE_BILL_PAYMENT_ID_EMPTY("4078", "删除销帐记录时, 付款流水号为空 "),
    UPDATE_BILL_STATE_EMPTY("4079", "更新销帐记录表时, 状态为空 "),
    UPDATE_BILL_STATE_DATE_EMPTY("4080", "更新销帐记录表时, 状态变更日期为空 "),
    UPDATE_BILL_INVOICE_ID_EMPTY("4081", "更新销帐记录表时, 发票标识为空 "),
    UPDATE_BILL_BILL_ID_EMPTY("4082", "更新销帐记录表时, 销帐流水号为空 "),
    REVERSE_BILL_REVERSE_EMPTY("4083", "反销帐时, 传入的反销帐结构为空 "),
    REVERSE_BILL_SERIAL_TYPE_EMPTY("4084", "反销帐时, 传入的销帐流水号为空 "),
    REVERSE_PAY_REVERSE_EMPTY("4085", "冲正时, 传入的冲正结构为空 "),
    BALANCE_PAYOUT_BILL_ID_EMPTY("4086", "余额支出时, 销帐流水为空 "),
    BALANCE_PAYOUT_PAYOUT_DATE_EMPTY("4087", "余额支出时, 支出日期为空 "),
    BALANCE_PAYOUT_ACCT_BALANCE_ID_EMPTY("4088", "余额支出时, 余额帐本标识为空 "),
    ACCT_BALANCE_NOT_HAVE_SOURCE("4089", "余额帐本没有对应的余额来源记录 "),
    BALANCE_PAYOUT_PAYOUT_AMOUNT_EMPTY("4090", "余额支出时, 支出金额为空 "),
    LASTEST_BILL_INFO_EMPTY("4091", "查询最后一次销帐信息时，存放信息的结构为空 "),
    CASH_BILL_AMOUNT_LESS_CHARGE("4092", "销帐时，实时金额小于应收金额 "),
    CASH_BILL_DATA_CHANGE("4093", "销帐时，欠费信息已经发生变动，请重新查询 "),
    GROUP_AMOUNT_NOT_EQUAL_AMOUNT("4094", "付款方式组合计金额不等于实收金额 "),
    CALL_RT_VIREMENT_FAILED("4095", "调用实时下帐服务失败 "),
    REFUND_NOT_ENOUGH_BALANCE("4096", "退款时，退款金额大于余额帐本余额 "),
    REFUND_ACCT_BALANCE_ID_INVALID("4097", "退款时，申请退款的余额帐本不存在 "),
    REFUND_ACCT_BALANCE_BALANCE_NULL("4098", "退款时，余额帐本余额为空 "),
    REFUND_ACCT_BALANCE_ID_NULL("4099", "退款时，余额帐本标识为空 "),
    OWE_SWITCH_GET_ACCT_ID_FAILED("4100", "停复机处理时，获取帐户标识出错 "),
    INSERT_TRANSFER_LOG_EMPTY("4102", "插入余额转帐日志表时，传入的数组为空 "),
    INSERT_TRANS_LOG_ID_EMPTY("4103", "插入余额转帐日志表时，日志标识为空 "),
    INSERT_TRANS_LOG_SRC_BALANCE_EMPTY("4104", "插入余额转帐日志表时，源余额帐本标识为空 "),
    INSERT_TRANS_LOG_DEST_BALANCE_EMPTY("4105", "插入余额转帐日志表时，目标余额帐本标识为空 "),
    INSERT_TRANS_LOG_BALANCE_EMPTY("4106", "插入余额转帐日志表时，转帐金额为空 "),
    INSERT_TRANS_LOG_SRC_PAYMENT_EMPTY("4107", "插入余额转帐日志表时，源付款流水为空 "),
    INSERT_TRANS_LOG_DEST_PAYMENT_EMPTY("4108", "插入余额转帐日志表时，目标付款流水为空 "),
    INSERT_TRANS_LOG_STAFF_EMPTY("4109", "插入余额转帐日志表时，操作员工号为空 "),
    INSERT_TRANS_LOG_CREATED_DATE_EMPTY("4110", "插入余额转帐日志表时，生成日期为空 "),
    INSERT_TRANS_LOG_STATE_EMPTY("4111", "插入余额转帐日志表时，状态为空 "),
    INSERT_TRANS_LOG_STATE_DATE_EMPTY("4112", "插入余额转帐日志表时，状态变更日期为空 "),
    INSERT_RT_VIREMENT_LOG_VECTOR_EMPTY("4113", "插入实时结帐日期表时，传入的数组为空 "),
    INSERT_RT_VIREMENT_LOG_ID_EMPTY("4114", "插入实时结帐日期表时，日志标识为空 "),
    INSERT_RT_VIREMENT_LOG_STAFF_ID_EMPTY("4115", "插入实时结帐日期表时，操作员工号为空 "),
    INSERT_RT_VIREMENT_LOG_ACCT_ID_EMPTY("4116", "插入实时结帐日期表时，帐户标识为空 "),
    INSERT_RT_VIREMENT_LOG_AMOUNT_EMPTY("4117", "插入实时结帐日期表时，结帐金额为空 "),
    INSERT_RT_VIREMENT_LOG_CREATED_DATE_EMPTY("4118", "插入实时结帐日期表时，生成日期为空 "),
    INVALID_REFERENCE_DATE_FORMAT("4120", "查询帐务周期起始终止日期时，传入的参考日期格式不对 "),
    REFERENCE_DATE_NOT_BELONG_CYCLE("4121", "没有参考日期对应的帐务周期 "),
    STAFF_NO_REVERSE_OTHER_CYCLE_PAY("4122", "该工号没有隔帐期冲正的权限 "),
    STAFF_NO_REVERSE_OTHER_CYCLE_BILL("4123", "该工号没有隔帐期反销的权限 "),
    QUERY_MANAGE_ORG_ID_FAILED("4124", "无法获取该工号所能管理的运维机构 "),
    BSS_ORG_NOT_CONFIG_MANAGE_ORG("4125", "未配置运营机构与运维机构的管理关系 "),
    BSS_ORG_ID_NOT_EXIST("4126", "运营机构不存在 "),
    ORG_ID_NOT_EXIST("4127", "运维机构不存在 "),
    INSERT_BILL_DEPOSIT_AMOUNT_EMPTY("4128", "插入销帐表时，剩余金额为空 "),
    INSERT_PAYMENT_ACCT_ID_EMPTY("4129", "插入付款信息表时，帐户标识为空 "),
    STAFF_CANNOT_MANAGE_ACC_NBR("4131", "该工号没有操作该号码的权限 "),
    INVALID_REPRINT_QRY_FLAG("4133", "无效的发票重打信息查询标志 "),
    REPRINT_INVOICE_QUERY_EMPTY("4135", "发票重打信息查询时，传入的结构为空 "),
    STAFF_NO_INVALID_ACCT_BALANCE_TRANSFER("4136", "该工号没有注销用户余额转帐的权限 "),
    REPRINT_INVOICE_QUERY_VALUE_EMPTY("4138", "待完错误描述"),
    INVALID_REPRINT_INVOICE_QUERY_FLAG("4139", "待完错误描述"),
    BALANCE_GROUP_ID_NO_MEMBER("4140", "待完错误描述"),
    INVALID_FUND_LEVEL_MERGE_FLAG("4142", "待完错误描述"),
    INVALID_GET_FLAG_MERGE_FLAG("4143", "待完错误描述"),
    INT_BAL_ACCT_ITEM_PAYED_OUTID_EMPTY("4144", "待完错误描述"),
    INT_BAL_ACCT_ITEM_PAYED_ITEM_EMPTY("4145", "待完错误描述"),
    INT_BAL_ACCT_ITEM_PAYED_BALANCE_EMPTY("4146", "待完错误描述"),
    INT_BAL_ACCT_ITEM_PAYED_STATE_EMPTY("4147", "待完错误描述"),
    INT_BAL_ACCT_ITEM_PAYED_STATE_DATE_EMPTY("4148", "待完错误描述"),
    V_BALANCE_ACCT_ITEM_PAYED_EMPTY("4149", "待完错误描述"),
    NOT_CONFIG_BALANCE_ACCT_ITEM_TYPE("4152", "待完错误描述"),
    BALANCE_TYPE_NOT_CONFIG_ITEM_TYPE("4153", "待完错误描述"),
    SERVICE_REQUEST_QUERY_FLAG_ACTION_MISMATCH("4154", "待完错误描述"),
    INVALID_SERVICE_REQUEST_ACTION("4155", "待完错误描述"),
    PRE_CHANGE_CHANGED("4156", "待完错误描述"),
    INVALID_QUERY_ID_TYPE("4160", "待完错误描述"),
    LIMITED_ACTION_WITH_USER("4162", "待完错误描述"),
    ONCE_BILL_WITH_MANY_STATE("4163", "待完错误描述"),
    STAFF_CANNOT_REFUND_SPECIAL_BALANCE("4164", "待完错误描述"),
    STAFF_CANNOT_TRANSFER_SPECIAL_BALANCE("4165", "待完错误描述"),
    BALANCE_TRANSFER_LOG_NOT_EXIST("4169", "4169"),
    ROLL_BALANCE_TRANSFER_INPUT_EMPTY("4172", "4172"),
    ROLL_BALANCE_TRANSFER_ID_NULL("4173", "4173"),
    ROLL_BALANCE_TRANSFER_STAFF_ID_NULL("4174", "4174"),
    SRC_ACCT_BALANCE_NOT_CHANGE("4177", "4177"),
    DEST_ACCT_BALANCE_NOT_CHANGE("4178", "4178"),
    PASSWORD_NOT_MODIFY("4179", "4179"),
    PASSWORD_LENGTH_NOT_RANGE("4180", "4180"),
    ILLEGAL_PASSWORD("4181", "4181"),
    ACCT_BALANCE_NOT_ENOUGH_BALANCE("4182", "4182"),
    COMMIT_FO_STAFF_ID_EMPTY("4183", "4183"),
    COMMIT_FO_PAYMENT_ID_EMPTY("4184", "4184"),
    INVALID_UPDATE_BATCH_BILL_ACTION("4186", "4186"),
    INVALID_BILL_DEP_INVOICE_PRINT_FLAG("4187", "4187"),
    INVALID_TRUST_MODE("4188", "4188"),
    SEARCH_MIN_ACCT_ITEM_SOURCE_EMPTY("4189", "4189"),
    SEARCH_MIN_ACCT_ITEM_SOURCE_ILLEGAL("4190", "4190"),
    INVALID_BALANCE_ATM_PAYED_QUERY_FLAG("4191", "4191"),
    INVALID_BALANCE_PAYOUT_UPDATE_ACTION("4194", "4194"),
    INVALID_BALANCE_ATM_PAYED_UPDATE_FLAG("4196", "4196"),
    SERVICE_ID_IS_ERROR("4198", "4198"),
    TELIN_ERROR("4199", "4199"),
    DAILY_ORG_BSSINFO_ERROR("4200", "营业厅报表营业系统费用提取失败"),
    DAILY_ORG_ACCTINFO_ERROR("4201", "营业厅报表缴费数据提取失败"),
    DAILY_ORG_CHANGEREFUND_ERROR("4202", "营业厅报表获取零头提取失败"),
    DAILY_ORG_PAYMENTC0C_ERROR("4203", "营业厅日报获取payment-coc记录失败"),
    DAILY_ORG_PAYMENTC0F_ERROR("4204", "营业厅日报获取payment-cof记录失败"),
    DAILY_ORG_PAYMENTC0R_ERROR("4205", "营业厅日报获取payment-cor记录失败"),
    IMMEDIATE_VIREMENT_HAVE_OWE_FEE("4206", "4206"),
    INSERT_RT_VIREMENT_LOG_STATE_EMPTY("4207", "4207"),
    INSERT_RT_VIREMENT_LOG_CYCLE_EMPTY("4209", "4209"),
    INSERT_RT_VIREMENT_LOG_SERV_ID_EMPTY("4210", "4210"),
    IMMEDIATE_VIREMENT_CANNOT_DEPOSIT("4211", "4211"),
    STAFF_NO_REVERSE_IMMEDIATE_VIRE_PAY("4212", "4212"),
    MUST_SPECIFY_BILLING_CYCLE("4214", "4214"),
    BATCH_BILL_OWECHARGE_NEGATIVE("4215", "4215"),
    NOT_MATCH_TARIFF_INFO("4216", "4216"),
    MISS_DUE_PRICE_RULE_CONFIG("4218", "4218"),
    PRICE_RULE_NOT_INCLUDE_ITEM_TYPE("4220", "4220"),
    INVALID_DUE_REF_ITEM_TYPE("4221", "4221"),
    CANNOT_FIND_MATCH_PRICE_RULE("4222", "4222"),
    ITEM_CHARGE_QRY_SERV_ID_EMPTY("4223", "4223"),
    AGENT_BILL_GET_OWE_ACCT_INVALID_PARAMETER("4226", "4226"),
    INSERT_TIFTOMSG_ERR("4227", "4227"),
    SEARCH_JUDGE_CONDITION_INPUT_EMPTY("4228", "4228"),
    INVALID_CONDITION_REFERENCE_OBJECT("4229", "4229"),
    EXEC_REL_OPERATION_INPUT_EMPTY("4230", "4230"),
    INVALID_RELATION_OPERATOR("4231", "4231"),
    NOT_MATCH_CONDITION_ID("4232", "4232"),
    REL_OPERATOR_MISMATCH_REF_OBJECT_ATTR("4235", "4235"),
    GET_QUERY_CONTROL_INFO_INPUT_EMPTY("4237", "4237 "),
    NOT_MATCH_QUERY_CONTROL_CONDITION("4238", "4238"),
    NOT_CONFIG_QUERY_CONTROL_RULE("4240", "4240"),
    QUERY_CONTROL_STAFF_ID_NULL("4241", "4241"),
    QUERY_CONTROL_QUERY_FLAG_NULL("4242", "4242"),
    QUERY_CONTROL_QUERY_SOURCE_NULL("4243", "4243"),
    QUERY_CONTROL_QUERY_ITEM_NULL("4244", "4244"),
    QUERY_CONTROL_QUERY_VALUE_EMPTY("4245", "4245"),
    UPDATE_ACCT_ITEM_OWE_INCOMPLETE("4246", "4246"),
    REVERSE_BILL_CASH_BILL_MISMATCH("4247", "4247"),
    PROPRIETARY_REF_OBJECT("4251", "4251"),
    GET_REF_VAL_BALANCE_INPUT_NULL("4253", "4253"),
    GET_REF_VAL_BALANCE_QUERY_FLAG_NULL("4254", "4254"),
    GET_REF_VAL_BALANCE_UNKNOWN_QUERY_FLAG("4255", "4255"),
    GET_REF_VAL_BALANCE_QUERY_VALUE_NULL("4256", "4256"),
    INSERT_PAYMENT_SERV_ID_EMPTY("4257", "4257"),
    INSERT_PAYMENT_ACC_NBR_EMPTY("4258", "4258"),
    DEPOSIT_SERV_ID_EMPTY("4259", "4259"),
    DEPOSIT_ACC_NBR_EMPTY("4260", "4260"),
    DEPOSIT_OBJECT_TYPE_MISMATCH_INFO("4261", "4261"),
    GET_REF_VAL_BALANCE_STAFF_ID_NULL("4262", "4262"),
    QUERY_RECORD_OVERFLOW_CONFIG("4264", "4264"),
    INVALID_BILLING_MODE_QUERY_FLAG("4269", "待完错误描述"),
    UPDATE_ACCT_ITEM_ITEM_ID_EMPTY("4270", "待完错误描述"),
    SERV_ID_AND_NBR_MISMATCH("4271", "待完错误描述"),
    BATCH_INVOICE_MISS_EXCH_NO("4273", "4273"),
    BATCH_BILL_INCLUDED_FLAG_MISS("4275", "4275"),
    FETCH_RECORD_EXCEED_MAX_VALUE("4276", "4276"),
    STAFF_NO_PRINT_OTHER_INVOICE("4900", "该员工没有权限重打他人发票"),
    STAFF_NO_PRINT_BSS_ORG_INVOICE("4901", "该员工不能跨机构重打"),
    BILL_ITEM_ACCT_ITEM_EMPTY_ALL("4902", "发票归并三维标准为空"),
    DEPOSIT_AMOUNT_EMPTY("5000", "预存时传入的付款金额为空 "),
    DEPOSIT_AMOUNT_ZERO("5001", "预存时传入的付款金额为零 "),
    DEPOSIT_ACCT_ID_EMPTY("5002", "预存时传入的帐户标识为空 "),
    DEPOSIT_STAFF_ID_EMPTY("5003", "预存时传入的工号为空 "),
    DEPOSIT_OPERATION_TYPE_EMPTY("5004", "预存时传入的操作类型为空 "),
    DEPOSIT_SOURCE_TYPE_EMPTY("5005", "预存时传入的来源类型为空 "),
    DEPOSIT_SOURCE_DESC_EMPTY("5006", "预存时传入的来源描述为空 "),
    DEPOSIT_PAY_METHOD_EMPTY("5007", "预存时传入的付款方式为空 "),
    DEPOSIT_BALANCE_AMOUNT_EMPTY("5008", "预存时传入的预存金额为空 "),
    AUTO_BILLING_ACCT_ID_EMPTY("5100", "自动销帐时帐户标识为空 "),
    AUTO_BILLING_STAFF_ID_EMPTY("5101", "自动销帐时工号为空 "),
    AUTO_BILLING_INPUT_EMPTY("5102", "自动销帐时，传入的销帐信息结构为空 "),
    GET_JUDGE_CONDITION_ACCT_INVALID("6004", "获取预存判断条件时帐户标识为空 "),
    GET_JUDGE_CONDITION_STAFF_INVALID("6005", "获取预存判断条件时员工标识为空 "),
    GET_JUDGE_CONDITION_SOURCE_TYPE_EMPTY("6006", "获取预存判断条件时来源类型为空 "),
    GET_JUDGE_CONDITION_BALANCE_TYPE_INVALID("6007", "获取预存判断条件时余额类型为空 "),
    SERV_LEVEL_SERV_ID_EMPTY("6008", "预存级别判断结果为用户级别，但用户标识为空 "),
    ITEM_LEVEL_NOT_LEVEL_ATTR("6009", "预存级别判断结果为帐目级级别，但没有找到相应的预存配置扩展信息 "),
    ITEM_LEVEL_SERV_ID_EMPTY("6022", "预存为帐目组级别时，用户标识为空(用户帐目组) "),
    INVALID_DEPOSIT_LEVEL("6023", "系统无法识别的预存级别 "),
    TOO_MANY_DEPOSIT_LEVEL_CFG_RECORD("6024", "一条赠送条件对应多条的预存级别配置记录 "),
    TOO_MANRY_CONFER_RULE_RECORD("6025", "一条赠送条件对应多条的赠送规则 "),
    TOO_MANY_CONFER_RULE_DETAIL_RECORD("6026", "指定的赠送规则和赠送类型以及预存金额对应多条的赠送规则明细 "),
    TOO_MANY_VALID_DAYS_RULE_RECORD("6027", "一条赠送条件对应多条的有效期规则 "),
    TOO_MANY_VALID_DAYS_RULE_DETAIL_RECORD("6028", "指定的有效期规则以及预存金额对应多条的有效期规则明细 "),
    INVALID_UNIT_ID("6032", "无效的生效时间偏移单位 "),
    CONFER_INFO_QUERY_DEPOSIT_INFO_INVALID("6033", "查询预存赠送信息时,传入的查询参数无效 "),
    CONFER_INFO_QUERY_AMOUNT_INVALID("6034", "查询预存赠送信息时,传入的金额为空 "),
    BATCH_BILL_STAFF_ID_EMPTY("6038", "批量销帐时工号标识为空 "),
    INVALID_CONFER_TYPE("6039", "无效的预存赠送类型 "),
    ACCT_DEPUTY_ACC_NBR_NOT_EXIST("6040", "帐户代表号码不存在 "),
    GET_SWITCH_VALUE_STAFF_EMPTY("6041", "获取配置的系统开关值时, 传入的工号标识为空 "),
    GET_SWITCH_VALUE_SWITCH_EMPTY("6042", "获取配置的系统开关值时, 传入的系统开关标识为空 "),
    GET_CYCLE_BEGIN_DATE_FAILED("6043", "无法获取帐务周期起始日期 "),
    GET_CYCLE_END_DATE_FAILED("6044", "无法获取帐务周期终止日期 "),
    CONFER_VALUE_VECTOR_NOEQUAL_ONE("6045", "预存时, 赠送信息多于一条 "),
    INVALID_CALC_METHOD("6046", "无效的有效期计算规则 "),
    NOT_CONDITION_REF_OBJECT_ERROR("6053", "判断条件没有配置相应的参考对象"),
    NOT_RETURNRULE_ERROR("6056", "找不到相应的返还规则 "),
    TOO_MANY_RETURN_RULE("6057", "返还规则不配置 "),
    RETURN_RULE_VECTOR_NOEQUAL_ONE("6059", "预存时, 返还信息多于一条 "),
    RETURN_OBJECT_VECTOR_NOTREC_ERROR("6061", "返还对象为它人时,没有指定返还实例 "),
    RETURN_OBJECT_VECTOR_MORE_ERROR("6062", "返还对象为自己时,指定了其它返还实例 "),
    NOT_RETURN_STEP_ERROR("6066", "没有返还步骤信息 "),
    NOT_AVI_RETURN_STEP_ERROR("6067", "没有满足条件的返还步骤信息 "),
    STEP_MOTHTYPES_ERROR("6068", "返还月份类型不是相对或绝对 "),
    RETURN_STEP_CFG_ERROR("6069", "返还步骤配置错误 "),
    RETURN_STEP_EFF_ERROR("6070", "返还步骤配置错误,非第一步时配置了实时生效的对象 "),
    NOT_STEP_DEPAMOUNT_ERROR("6071", "返还步骤配置错误,没有配置返还额度 "),
    NOT_EFF_STEP_DETAIL_ERROR("6072", "没有满足条件的返还步骤 "),
    RETURN_OBJECT_RETURNVAL_ERROR("6073", "返还值配置错误,超出单步返还金额 "),
    STEP_DEPAMOUT_CFG_ERROR("6074", "返还额度大于当前余额或小于零 "),
    RETURN_OBJECT_TYPE_ERROR("6075", "返还规则的返还对象出错 "),
    NOT_RETURN_OBJECT_ERROR("6079", "没有返还对象 "),
    SELECT_RETINST_SOURCE_ERROR("6082", "查询返还实例来源关系表出错 "),
    SELECT_RETURN_LOG_ERROR("6085", "查询返还实例返还日志表出错 "),
    TOOMANYD_STEP_DEPAMOUT_ERROR("6086", "返还步骤配置错误,配置了多个返还额度 "),
    MON_RETURN_ONE_MORE_ERROR("6087", "存在历史未激活数据 "),
    VALID_BALANCE_LESS_RETURN_AMOUNT("6088", "余额小于要返还的金额 "),
    RETURN_OBJECT_NOT_SELF_OR_OTHERS("6089", "返还规则的返还对象不是自己或他人 "),
    HAVE_BALANCE_RETURN_LOG_REC_ERROR("6090", "当月已存在返还记录 "),
    STAFF_CANNOT_TRANSFER_OWEACCT_BALANCE("6092", "帐户处于欠费状态不能进行结转操作 "),
    INSERT_PLATFORM_EMPTY_ERROR("6094", "平台标识为空 "),
    MORE_PLATFORM_TABLE_ERROR("6096", "平台配置了多个接口表 "),
    NOT_PLATFORM_TABLE_ERROR("6097", "没有配置平台接口表 "),
    NOT_PAYMENT_PLATFORM_EXIT_ERROR("6098", "找不到PAYMENT_PLATFORM记录 "),
    REFUND_MEDIUM_FLAG_EMPTY("6100", "待完错误描述"),
    REFUND_MEDIUM_CHECKNO_EMPTY("6101", "待完错误描述"),
    REFUND_MEDIUM_ERROR("6102", "待完错误描述"),
    RT_QUERY_MUST_RETURN_ALL_OWE("6103", "立即结帐必须查询全部历史欠费"),
    CASH_BILL_FEE_QUERY_FLAG_ERROR("6104", "待完错误描述"),
    OBJECT_TYPE_NOT_CONFIG_MEMBER_SOURCE("6106", "6106"),
    INSERT_ACCT_BALANCE_OBJECT_EMPTY("6107", "6107"),
    INSERT_ABO_BALANCE_ID_NULL("6108", "6108"),
    INSERT_ABO_OBJECT_TYPE_EMPTY("6109", "6109"),
    INSERT_ABO_OBJECT_ID_NULL("6110", "6110"),
    COND_TYPE_SOURCE_MEMBER_ONLY_OFFER("6115", "6115"),
    NOT_FOUND_OBJECT_TYPE_MEMBER("6116", "6116"),
    INVALID_PRODUCT_OFFER_TYPE("6119", "6119"),
    SWITCH_SINGLE_FLOW_CONFIG_ERROR("6120", "6120"),
    AUTO_CONFER_RETURNRULE_TYPE_ERROR("6168", "自动赠送的返还规则其返还对象不能为他人 "),
    NOT_DISP_JUDGECONDITION_ERROR("6171", "没有配置平台的档案验证条件 "),
    SERV_DONOT_DISP_THIS_PLATFORM_ERROR("6172", "此用户不能进行这个平台的预存 "),
    JUDGE_RETURNRULESTEP_CONDITION_ERROR("6173", "不满足返还条件 "),
    RETURN_MON_RETURN_FLAG_ERROR("6174", "返还规则的返还限制非1或2 "),
    NO_BALANCE_RETURN_LOG_DATA_ERROR("6175", "余额激活记录不存在 "),
    GET_CONDITION_TYPE_INVALID("6176", "未指定判断条件类型 "),
    MUTEX_CONDI_OPERATOR_ERROR("6177", "互斥参考对象的运行符非等号 "),
    STAFF_NO_NOTACTIVE_BALANCE_TRANSFER("6180", "员工没有结转未激活余额的权限 "),
    ONE_ACCT_BALANCE_MORE_RETURN_RULE_ERROR("6181", "一条帐本对应多条返还规则错误 "),
    NOT_TRANSFER_ALL_NOTACTIVE_BAL_ERROR("6182", "没有全额结转未激活的余额 "),
    NOT_REFUNDS_ALL_NOTACTIVE_BAL_ERROR("6183", "没有全额提取未激活的余额 "),
    STAFF_CANNOT_REFUND_NOTACTIVE_BALANCE("6184", "员工没有提取未激活余额的权限 "),
    DEPOTISTELIN_ACCNBR_EMPTY("6185", "智能网预存 接入号码为空 "),
    DEPOTISTELIN_PAYMENTOPTIONTYPE_EMPTY("6186", "智能网预存 操作类型为空 "),
    DEPOTISTELIN_SOURCETYPE_EMPTY("6187", "智能网预存 预存来源为空 "),
    DEPOTISTELIN_PAYMENTMETHOD_EMPTY("6188", "智能网预存 付款方式为空 "),
    DEPOTISTELIN_PAYEDMETHOD_EMPTY("6189", "智能网预存 实际付方式为空 "),
    DEPOTISTELIN_CHARGE_EMPTY("6190", "智能网预存 充值金额为空 "),
    APTITUDE_DEPOSIT_ERROR("6191", "智能网预存 调用智能网接口出错 "),
    DEPOTISTELIN_STAFF_ID_EMPTY("6192", "智能网预存 工号为空 "),
    DEPOTISTELIN_ACCTID_EMPTY("6193", "智能网预存 合同号为空 "),
    DEPOTISTELIN_SERVID_EMPTY("6194", "智能网预存 用户标识为空 "),
    JUDGE_EXTEND_MORE_QUERYFLAG("6195", "A_REF_OBJECT_EXTEND配置了多条费用级别信息 "),
    QRY_AGENT_BALANCE_SOURCE_QRY_FLAG_ERROR("6198", "待完错误描述"),
    QRY_AGENT_BALANCE_PAYOUT_QRY_FLAG_ERROR("6203", "待完错误描述"),
    INSERT_AGENT_INFO_EMPTY("6204", "待完错误描述"),
    INSERT_AGENT_INFO_BSSORGID_EMPTY("6205", "待完错误描述"),
    INSERT_AGENT_INFO_BSSORGNAME_EMPTY("6206", "待完错误描述"),
    INSERT_AGENT_INFO_BALANCE_EMPTY("6207", "待完错误描述"),
    INSERT_AGENT_INFO_CREDIT_EMPTY("6208", "待完错误描述"),
    INSERT_AGENT_INFO_TIPAMOUNT_EMPTY("6209", "待完错误描述"),
    INSERT_AGENT_INFO_UNPAYQUOTA_EMPTY("6210", "待完错误描述"),
    INSERT_AGENT_INFO_CREATEDDATE_EMPTY("6211", "待完错误描述"),
    INSERT_AGENT_INFO_STATE_EMPTY("6212", "待完错误描述"),
    INSERT_AGENT_INFO_STATEDATE_EMPTY("6213", "待完错误描述"),
    UPDATE_AGENT_INTO_EMPTY("6214", "待完错误描述"),
    UPDATE_AGENT_INFO_OPERTYPE_ERROR("6215", "待完错误描述"),
    UPDATE_BSS_ORG_BSSORGID_EMPTY("6217", "待完错误描述"),
    UPDATE_BSS_ORG_BSSORGCODE_EMPTY("6218", "待完错误描述"),
    UPDATE_BSS_ORG_BSSNAME_EMPTY("6219", "待完错误描述"),
    UPDATE_BSS_ORG_STATE_EMPTY("6220", "待完错误描述"),
    AGENT_MGR_NOT_PAYOUTREC("6221", "待完错误描述"),
    AGENT_MGR_PAYOUT_PAYMENTID_IS_EMPTY("6222", "待完错误描述"),
    AGENT_MGR_PAYOUT_BSSORGID_IS_EMPTY("6223", "待完错误描述"),
    AGENT_MGR_PAYOUT_STAFFID_IS_EMPTY("6224", "待完错误描述"),
    AGENT_MGR_PAYOUTAMOUNT_IS_EMPTY("6225", "待完错误描述"),
    AGENT_MGR_PAYOUT_STATE_IS_EMPTY("6226", "待完错误描述"),
    AGENT_MGR_NOT_BALANCE_SOURCE_REC("6227", "待完错误描述"),
    AGENT_MGR_MORE_BALANCE_SOURCE_REC("6228", "待完错误描述"),
    AGENT_REVERSE_EMPTY("6229", "待完错误描述"),
    AGENT_REVERSE_OPERINCOMEID_EMPTY("6230", "待完错误描述"),
    AGENT_REVERSE_REVERSEAMOUNT_EMPTY("6231", "待完错误描述"),
    AGENT_REVERSE_STAFFID_EMPTY("6232", "待完错误描述"),
    AGENT_REVERSE_OPERTYPE_EMPTY("6233", "待完错误描述"),
    AGENT_BALANCE_BALANCE_CHANGE_ERROR("6234", "待完错误描述"),
    AGENT_REFUND_EMPTY("6235", "待完错误描述"),
    AGENT_REFUND_REFUNDMOUNT_EMPTY("6236", "待完错误描述"),
    AGENT_REFUND_STAFFID_EMPTY("6237", "待完错误描述"),
    AGENT_REFUND_BSSORGID_EMPTY("6238", "待完错误描述"),
    AGENT_INFO_MORE_REC_ERROR("6239", "待完错误描述"),
    AGENT_DEPOSIT_EMPTY("6240", "待完错误描述"),
    AGENT_DEPOSIT_BSSORGID_EMPTY("6241", "待完错误描述"),
    AGENT_DEPOSIT_STAFFID_EMPTY("6242", "待完错误描述"),
    AGENT_DEPOSIT_AMOUNT_EMPTY("6243", "待完错误描述"),
    AGENT_DEPOSIT_OPERTYPE_EMPTY("6244", "待完错误描述"),
    AGENT_REFUND_MORE_BALANCE("6247", "待完错误描述"),
    GET_RETURN_OBJ_CONSUME_ERROR("6248", "待完错误描述"),
    GET_RETURN_OBJ_CONSUME_ZERO_ERROR("6249", "待完错误描述"),
    STAFF_NOT_RETURN_BACKOUT_SERV_BALANCE("6250", "待完错误描述"),
    STAFF_NOT_RETURN_SERV_ACCT_CHANGE_BALANCE("6251", "待完错误描述"),
    AGENT_BALANCE_OVERFLOW("6252", "待完错误描述"),
    DAILY_REVERSE_QUOTA_OVERFLOW("6253", "待完错误描述"),
    INSERT_CASH_BILL_MIDDLE_ERROR("6255", "待完错误描述"),
    INSERT_CBM_BALANCE_ID_EMPTY("6256", "待完错误描述"),
    INSERT_CBM_ITEM_ID_EMPTY("6257", "待完错误描述"),
    INSERT_CBM_BALANCE_EMPTY("6258", "待完错误描述"),
    INSERT_BAL_ACCT_ITEM_PAYED_ERROR("6259", "待完错误描述"),
    CAL_DUE_FEEBILL_EMPTY("6300", "拆分销帐计算滞纳金时，欠费结构为空"),
    CAL_DUE_FEEBILL_HAVE_MULTIACCT("6301", "拆分销帐计算滞纳金时，欠费结构存在多个账户标识"),
    CAL_DUE_FEEBILL_CYCLE_EMPTY("6302", "拆分销帐计算滞纳金时，欠费结构帐期标识为空"),
    CAL_DUE_FEEBILL_ITEM_TYPE_EMPTY("6303", "拆分销帐计算滞纳金时，欠费结构账目类型标识为空"),
    DUE_RATE_INFO_NOT_EXIST("6304", "拆分销帐计算滞纳金时，滞纳金计算参数不存在"),
    SPLIT_AUTO_BILLING_FEEBILL_EMPTY("6310", "拆分销帐时，欠费结构为空"),
    SPLIT_AUTO_BILLING_FEEBILL_CYCLE_EMPTY("6311", "拆分销帐时，欠费结构帐期标识为空"),
    SPLIT_AUTO_BILLING_FEEBILL_SERV_ITEM_EMPTY("6312", "拆分销帐时，欠费结构用户标识或账目类型标识为空"),
    SPLIT_AUTO_BILLING_FEEBILL_AMOUNT_EMPTY("6313", "待完错误描述"),
    SPLITAUTOBILLING_CHARGE_LESSTHAN_BILLEDCHARGE("6314", "待完错误描述"),
    SPLITAUTOBILLING_DUE_NOT_EXIST("6315", "待完错误描述"),
    SPLITAUTOBILLING_COUNTERACT_NEGATIVEITEM_ERROR("6316", "待完错误描述"),
    BALANCE_SOURCE_REFUND_COUNTERACT_ERROR("6410", "拆分销帐时，对抵余额来源中退款记录出错"),
    INSERT_PAYMENT_EXTEND_VECTOR_EMPTY("6600", "待完错误描述"),
    INSERT_PAYMENT_EXTEND_PAYMENT_ID_EMPTY("6601", "待完错误描述"),
    INSERT_PAYMENT_EXTEND_EXTEND_TYPE_EMPTY("6602", "待完错误描述"),
    INSERT_PAYMENT_EXTEND_EXTEND_VALUE_EMPTY("6603", "待完错误描述"),
    PAYMENT_FUNDCOMMIT_USE_CS_REVERSE("6609", "待完错误描述"),
    PAYMENT_CRM_UNALLOWED_REVERSE("6610", "待完错误描述"),
    BALANCE_REMINDER_BILLING_MODE_MISMATCH("6615", "待完错误描述"),
    INVALID_REMINDER_BALANCE("6616", "待完错误描述"),
    BALANCE_REMINDER_NEGATIVE_BALANCE("6617", "待完错误描述"),
    INVALID_QUERY_ACCT_INFO_FLAG("6618", "待完错误描述"),
    NOT_QUERY_ACCT_INFO_VALUE("6619", "待完错误描述"),
    CUST_TYPE_ID_IS_NULL("6621", "待完错误描述"),
    BN_ACCT_INFO_STAFF_EMPTY("6622", "待完错误描述"),
    BIZ_NAVIGATOR_NOT_CONFIG("6623", "待完错误描述"),
    BIZ_NAVIGATOR_NOT_ALLOW("6624", "待完错误描述"),
    BZ_BALANCE_QUERY_ERR("6625", "待完错误描述"),
    BZ_PAY_ERR("6626", "待完错误描述"),
    INVALID_BINDING_SERV_ACTION("6627", "待完错误描述"),
    INVALID_ACTION("6630", "待完错误描述"),
    INVALID_SERVICE_LIMIT_MODE("6631", "待完错误描述"),
    OWE_ERROR_INVALID_REMINDER("6632", "待完错误描述"),
    TRUST_TO_DEPOSIT_UNALLOWED("6641", "待完错误描述"),
    INSERT_GLOBE_ACCT_ITEM_ID_VECTOR_EMPTY("6643", "待完错误描述"),
    SERV_ACCT_INFO_ERROR_QUERY("7000", "查询帐务关系定制表出错 "),
    SERV_ACCT_INFO_ERROR_NEXT("7001", "获取帐务定制关系出错 "),
    SERV_ACCT_INFO_NOT_EXIST("7002", "帐务定制关系不存在 "),
    BILL_REQUEMENT_INFO_NOT_EXIST("7005", "发票要求信息不存在 "),
    BILL_FORMAT_INFO_NOT_EXIST("7008", "帐单格式信息不存在 "),
    SORT_BILL_ITEM_ERROR_INSERT("7013", "插入普通归并帐单项出错 "),
    SORT_BILL_ITEM_SP_ERROR_INSERT("7014", "插入特殊归并帐单项出错 "),
    SORT_BILL_ITEM_ERROR_QUERY("7015", "查询归并帐单项出错 "),
    SORT_BILL_ITEM_ERROR_NEXT("7016", "获取归并帐单项出错 "),
    SOTR_ITEM_ID_NOT_EXIST("7017", "获取临时存放帐单项表帐单项序列号不存在 "),
    SOTR_ITEM_ID_ERROR_FETCH("7018", "获取临时存放帐单项序列号出错 "),
    SORT_BILL_ITEM_SP_CYCLE_ERROR_INSERT("7021", "按帐期插入特殊归并帐单项出错 "),
    SORT_BILL_ITEM_CYCLE_ERROR_INSERT("7022", "按帐期插入普通归并帐单项出错 "),
    BILL_INFO_BY_ID_ERROR_QUERY("7026", "查询销帐记录出错 "),
    BILL_INFO_BY_ID_ERROR_NEXT("7027", "获取销帐记录出错 "),
    PAYINFO_BY_ID_ERROR_QUERY("7028", "查询付款记录出错 "),
    PAYINFO_BY_ID_ERROR_NEXT("7029", "获取付款记录出错 "),
    STAFF_INFO_ERROR_QUERY("7032", "查询操作员信息 "),
    STAFF_INFO_ERROR_NEXT("7033", "获取操作员信息 "),
    SWITCH_VALUE_ERROR_QUERY("7034", "查询系统开关信息出错 "),
    PRINT_MONEY_ERROR_QUERY("7035", "查询实收总金额出错 "),
    BILL_INFO_BY_CYCLE_ERROR_QUERY("7036", "按帐期查询销帐信息出错 "),
    BILL_INFO_BY_CYCLE_ERROR_NEXT("7037", "按帐期获取销帐信息出错 "),
    ACCT_ITEM_BY_CYCLE_ERROR_UPDATE("7042", "按帐期更新帐目表出错 "),
    ACCT_ITEM_BY_BILLID_ERROR_UPDATE("7043", "按销帐流水更新帐目表出错 "),
    QUERY_PRINT_MONEY_NOT_EXIST("7044", "实收总金额不存在 "),
    BILLING_CYCLE_INFO_NOT_EXIST("7046", "帐务周期不存在 "),
    PRINT_BILL_SERIAL_NBR_NOT_EXIST("7047", "要打印的销帐流水不存在 "),
    STAFF_ID_NOT_EXIST("7048", "要查询的操作员不存在 "),
    PRINT_PAY_SERIAL_NBR_NOT_EXIST("7049", "要打印的付款流水不存在 "),
    PRINT_BILL_NOT_ACTIVE_STATE("7050", "要打印的流水不是销帐状态"),
    PRINT_PAY_NOT_ACTIVE_STATE("7051", "要打印的付款流水不是有效状态 "),
    INVOICE_NUM_MORE_ONE("7052", "该发票记录数多于一条 "),
    PRINT_TOO_TIME("7053", "打印次数超过了系统设置的最大打印次数 "),
    ACC_NBR_NOT_EXIST("7054", "通过帐户查询用户号码不存在 "),
    SERV_INFO_ERROR_QUERY("7055", "查询用户信息出错 "),
    TRUST_SEND_INFO_NOT_EXIST("7060", "托收号对应的托收信息不存在 "),
    BILLID_SHOULD_MONEY_ERROR_QUERY("7061", "查询销帐流水对应的应收金额出错 "),
    DONOT_GET_INVOICE("7067", "不能获取到发票记录 "),
    BILL_INFO_NOT_FOUND("7074", "打印发票查询销帐记录信息不存在  "),
    BILL_SERIAL_IS_EMPTY("7077", "生成发票时传入销帐流水号为空 "),
    ACCT_ID_EMPTY("7078", "按帐期生成发票时传入帐户标识为空 "),
    BILING_CYCLE_ID_EMPTY("7079", "按帐期生成发票时传入帐期标识为空 "),
    PAY_SERIAL_IS_EMPTY("7080", "生成收据时传入付款流水号为空 "),
    INVOICE_FLAG_PARAM_ERROR("7081", "输入参数票据生成依据标识出错 "),
    INVOICE_BILL_FLAG_PARAM_ERROR("7082", "输入参数是否触发销帐标识出错"),
    RECEIPT_CLASS_PARAM_ERROR("7083", "输入参数票据类型标识出错 "),
    INVOICE_PRINT_FLAG_PARAM_ERROR("7084", "输入参数票据打印分项方式出错 "),
    SERV_ACCT_INFO_EMPTY("7085", "传入帐务定制关系为空 "),
    CHILD_BILL_ITEM_EMPTY("7089", "帐单项子节点为空 "),
    BILL_ITEM_INFO_EMPTY("7092", "传入帐单项信息为空"),
    INVOICE_RECORD_INFO_EMPTY("7093", "发票记录为空 "),
    INVOICE_PRINT_EMPTY("7094", "传入打印发票格式出错 "),
    PRINT_INVOICE_PAY_FLAG_EMPTY("7095", "打印发票时传入是否付款标识为空"),
    PRINT_INVOICE_PAY_FLAG_ERROR("7096", "打印发票时传入无效付款标识出错 "),
    PRINT_INVOICE_BILL_FLAG_EMPTY("7097", "打印发票时传入是否触发销帐标识为空 "),
    PRINT_INVOICE_BILL_FLAG_ERROR("7098", "打印发票时传入无效触发销帐标识 "),
    PRINT_INVOICE_CLASS_EMPTY("7099", "打印发票时传入票据类型标识为空 "),
    PRINT_INVOICE_CLASS_ERROR("7100", "打印发票时传入无效票据类型标识 "),
    PRINT_INVOICE_PRINT_FLAG_EMPTY("7101", "打印发票时打印分页标识为空 "),
    PRINT_INVOICE_PRINT_FLAG_ERROR("7102", "打印发票时传入无效的打印分页标识 "),
    PRINT_INVOICE_STAFF_EMPTY("7103", "打印发票时传入操作员标识为空 "),
    PRINT_INVOICE_CYCLE_EMPTY("7104", "打印发票时传入帐期标识为空 "),
    PRINT_INVOICE_TRUSTID_EMPTY("7105", "打印发票时传入托收单号为空 "),
    PRINT_INVOICE_TRUST_DATE_EMPTY("7106", "打印发票时传入托收日期为空 "),
    BILL_INFO_ID_EMPTY("7107", "销帐记录标识为空 "),
    PAYMENT_INFO_AMOUNT_EMPTY("7108", "付款记录信息金额为空 "),
    PAYMENT_INFO_METHOD_EMPTY("7109", "付款记录信息付款方式为空 "),
    PRINT_INVOICE_BILLID_EMPTY("7110", "打印发票传入的销帐流水为空 "),
    BILL_INFO_ACCT_EMPTY("7111", "销帐记录ACCTID为空 "),
    SWITCH_VALUE_EMPTY("7112", "系统开关值为空 "),
    INVOICE_INFO_PRINT_COUNT_EMPTY("7113", "发票记录中打印次数为空 "),
    INVOICE_INFO_ID_EMPTY("7114", "发票记录中发票流水为空 "),
    DONOT_GET_NON_FORMAT("7115", "不能获取到非发票格式  "),
    PRINT_INVOICE_PAYID_EMPTY("7116", "打印发票传入的付款流水为空 "),
    BILL_ITEM_ID_IS_EMPTY("7117", "帐单项标识为空  "),
    BILLING_CYCLE_IS_EMPTY("7118", "帐期标识为空 "),
    ACCNBR_IS_EMPTY("7119", "电话号码为空 "),
    BILL_CHARGE_ERROR_QUERY("7120", "提供给计费查询往月欠费出错 "),
    BILL_CURBALANCE_ERROR_QUERY("7121", "提供给计费查询当前余额出错 "),
    INVOICE_EXTEND_ID_SEQ_NOT_EXIST("7123", "获取发票打印详细信息标识不存在  "),
    INSERT_INVOICE_DETAIL_VECTOR_EMPTY("7125", "插入记录发票详细信息传入的帐单项结构体为空"),
    BILL_INFO_DEPOSITAMOUNT_EMPTY("7127", "销帐记录预存金额为空 "),
    NOT_BANK_STAFF_ID("7128", "当前打印工号非银行工号 "),
    COMMISION_MANAGER_STAFF_EMPTY("8003", "代收关系维护时,传入的工号为空 "),
    COMMISION_MANAGER_ACC_NBR_EMPTY("8004", "代收关系维护时,电话号码为空 "),
    COMMISION_MANAGER_ACTION_EMPTY("8005", "代收关系维护时,动作标识为空 "),
    COMMISION_RELATION_EXIST("8006", "代收关系不存在 "),
    COMMISION_MANAGER_ACTION_INVALID("8007", "无效的代收关系维护标识 "),
    DUE_AUDIT_LOG_ERROR_SELECT("9005", "查询滞纳金审核记录出错 "),
    DUE_AUDIT_LOG_ERROR_FETCH("9006", "获取滞纳金审核记录出错 "),
    DUE_AUDIT_LOG_ERROR_INSERT("9007", "插入滞纳金审核记录出错 "),
    DUE_AUDIT_LOG_ERROR_UPDATE("9008", "修改滞纳金审核记录出错 "),
    INVALID_ADJUST_DUE_QRY_FLAG("9013", "无效的违约金查询标识 "),
    ADJUST_DUE_RECORD_NOT_EXIST("9014", "违约金调整记录不存在 "),
    TOO_MANY_ADJUST_DUE_RECORD("9015", "多于一条未处理的违约金调整记录 "),
    INVALID_ADJUST_DUE_UPDATE_FLAG("9016", "无效的违约金记录更新标识 "),
    FETCH_DUE_AUDIT_ID_ERROR("9017", "获取滞纳金审核日志SEQ出错 "),
    DUE_ADJUST_UNDO_FLAG_ERROR("9018", "对滞纳金调整进行回退时，传入审核标识出错 "),
    DUE_ADJUST_APPLY_ADJUST_REASON_EMPTY("9019", "滞纳金减免申请，传入调整原因为空"),
    DUE_ADJUST_APPLY_ADJUST_VALUE_EMPTY("9020", "滞纳金减免申请，传入调整值为空"),
    DUE_ADJUST_APPLY_ADJUST_TYPE_EMPTY("9021", "滞纳金减免申请，传入调整类型为空"),
    DUE_ADJUST_APPLY_ACCT_ID_EMPTY("9022", "滞纳金减免申请，传入帐户标识为空"),
    DUE_ADJUST_QUERY_EMPTY("9023", "传入的查询滞纳金调整记录结构为空 "),
    DUE_ADJUST_APPLY_EMPTY("9024", "传入的滞纳金调整申请结构为空 "),
    DUE_ADJUST_INFO_EMPTY("9025", "插入滞纳金调整记录时，传入的调整记录结构为空 "),
    DUE_ADJUST_QUERY_FLAG_EMPTY("9026", "查询滞纳金调整记录，传入的查询标识为空 "),
    DUE_ADJUST_QUERY_VALUE_EMPTY("9027", "查询滞纳金调整记录，传入的查询值为空 "),
    INVALID_DUE_ADJUST_QRY_FLAG("9028", "无效的滞纳金调整记录查询标识 "),
    INSERT_DUE_ADJUST_ACCT_ID_EMPTY("9029", "插入滞纳金调整记录，传入的帐户标识为空 "),
    INSERT_DUE_ADJUST_ADJUST_TYPE_EMPTY("9030", "插入滞纳金调整记录，传入的调整类型为空 "),
    INSERT_DUE_ADJUST_ADJUST_VALUE_EMPTY("9031", "插入滞纳金调整记录，传入的调整值为空 "),
    INSERT_DUE_ADJUST_STAFF_ID_EMPTY("9032", "插入滞纳金调整记录，传入的操作员为空 "),
    INSERT_DUE_ADJUST_ADJUST_REASON_EMPTY("9033", "插入滞纳金调整记录，传入的调整原因为空 "),
    INSERT_DUE_ADJUST_AUDIT_ID_EMPTY("9034", "插入滞纳金调整记录，传入的审核日志标识为空 "),
    QUERY_DUE_AUDIT_ACCT_ID_EMPTY("9035", "查询滞纳金审核记录，传入的帐户标识为空 "),
    UPDATE_DUE_AUDIT_CHECK_FLAG_EMPTY("9036", "滞纳金审核更新审核日志，传入审核标识为空 "),
    DUE_ADJUST_CHECK_EMPTY("9037", "滞纳金调整审核，传入审核结构为空 "),
    DUE_AUDIT_QUERY_EMPTY("9038", "滞纳金审核日志查询，传入查询结构为空 "),
    DUE_AUDIT_LOG_ID_LIST_EMPTY("9039", "滞纳金审核日志标识组为空 "),
    DUE_AUDIT_QUERY_FLAG_EMPTY("9040", "查询滞纳金审核记录，传入的查询标识为空 "),
    DUE_AUDIT_QUERY_VALUE_EMPTY("9041", "查询滞纳金审核记录，传入的查询值为空 "),
    INVALID_DUE_AUDIT_QRY_FLAG("9042", "无效的滞纳金审核记录查询标识 "),
    DUE_ADJUST_APPLY_FLAG_ERROR("9043", "滞纳金减免申请，传入审核标识出错 "),
    DUE_ADJUST_APPLY_FLAG_EMPTY("9044", "滞纳金减免申请，传入审核标识为空  "),
    INSERT_DUE_AUDIT_ACCT_ID_EMPTY("9045", "插入滞纳金审核记录，传入帐户标识为空 "),
    INSERT_DUE_AUDIT_ADJUST_TYPE_EMPTY("9046", "插入滞纳金审核记录，传入调整类型为空"),
    INSERT_DUE_AUDIT_ADJUST_VALUE_EMPTY("9047", "插入滞纳金审核记录，传入调整值为空"),
    INSERT_DUE_AUDIT_STAFF_ID_EMPTY("9048", "插入滞纳金审核记录，传入操作员标识为空"),
    INSERT_DUE_AUDIT_ADJUST_REASON_EMPTY("9049", "插入滞纳金审核记录，传入调整原因为空"),
    DUE_ADJUST_CHECK_LOGID_LIST_EMPTY("9050", "滞纳金审核，传入审核日志列表为空 "),
    DUE_ADJUST_CHECK_TYPE_EMPTY("9051", "滞纳金审核，传入审核类型为空 "),
    DUE_ADJUST_CHECK_TYPE_ERROR("9052", "滞纳金审核，传入审核类型出错 "),
    DUE_ADJUST_CHECK_FLAG_EMPTY("9053", "滞纳金审核，传入审核标识为空"),
    DUE_ADJUST_CHECK_STAFF_ID_EMPTY("9054", "滞纳金审核，传入操作员标识为空"),
    INVALID_DUE_ADJUST_CHECK_FLAG("9055", "无效的滞纳金审核标识 "),
    DUE_ADJUST_CHECK_REASON_EMPTY("9056", "滞纳金审核，传入审核原因为空"),
    DUE_ADJUST_CHECK_LOG_ID_EMPTY("9057", "滞纳金审核，传入审核日志标识为空"),
    UPDATE_DUE_AUDIT_CHECK_FLAG_ERROR("9058", "更新滞纳金审核日志，传入审核标识出错 "),
    DUE_ADJUST_APPLY_STAFF_ID_EMPTY("9059", "滞纳金减免申请，传入操作员标识为空 "),
    UPDATE_DUE_AUDIT_CHECK_REASON_EMPTY("9060", "更新滞纳金审核日志，传入审核原因为空 "),
    ADJUST_AUDIT_QUERY_EMPTY("9061", "传入调帐审核日志查询结构为空 "),
    ADJ_AUD_QRY_BY_ID_LIST_EMPTY("9062", "按照审核日志标识查询调帐审核日志，传入的标识列表为空 "),
    INSERT_ADJ_AUD_APPLY_EMPTY("9063", "插入调帐审核日志，传入的调帐申请结构为空 "),
    UPDATE_ADJ_AUD_CHECK_EMPTY("9064", "更新调帐审核日志，传入调帐审核结构为空 "),
    INSERT_ADJ_AUD_APPLY_FLAG_EMPTY("9067", "插入调帐审核日志, 传入的自动申请标识为空 "),
    INVALID_ADJUST_APPLY_FLAG("9068", "无效的自动申请标识 "),
    INSERT_ADJ_AUD_FOREADJUST_EMPTY("9069", "插入调帐审核日志, 传入的否是帐前调帐标识为空"),
    INVALID_IS_FORE_ADJUST_FLAG("9070", "无效的是否帐前调帐标识 "),
    INSERT_ADJ_AUD_ACCT_ID_EMPTY("9071", "插入调帐审核日志，传入的ACCTID为空"),
    INSERT_ADJ_AUD_SERV_ID_EMPTY("9072", "插入调帐审核日志，传入的SERVID为空"),
    INSERT_ADJ_AUD_ADJUST_TYPE_EMPTY("9073", "插入调帐审核日志，传入的调帐类型为空"),
    INSERT_ADJ_AUD_ACCT_ITEM_ID_EMPTY("9074", "插入调帐审核日志，调帐类型为百分比，传入的调帐帐目类型为空 "),
    INSERT_ADJ_AUD_ACCT_ITEM_CHARGE_EMPTY("9075", "插入调帐审核日志，调帐类型为百分比，传入的调帐帐目金额为空 "),
    INSERT_ADJ_AUD_ADJ_ACCT_ITEM_EMPTY("9076", "插入调帐审核日志，传入被调帐目类型为空"),
    INSERT_ADJ_AUD_ADJ_CHARGE_EMPTY("9077", "插入调帐审核日志，传入被调帐目类型值为空"),
    INSERT_ADJ_AUD_CYCLE_EMPTY("9078", "插入调帐审核日志，传入帐务周期为空"),
    INSERT_ADJ_AUD_STAFF_ID_EMPTY("9079", "插入调帐审核日志，传入操作员标识为空"),
    INSERT_ADJ_AUD_REASON_EMPTY("9080", "插入调帐审核日志，传入调帐原因为空"),
    UPDATE_ADJ_AUD_CHECK_REASON_EMPTY("9081", "更新调帐审核日志，传入调帐审核原因为空 "),
    INVALID_ADJUST_AUDIT_QRY_FLAG("9083", "调帐审核日志查询，传入无效的查询标识 "),
    INVALID_ADJUST_TYPE("9085", "无效的调帐类型 "),
    ADJUST_CHECK_LOGID_LIST_EMPTY("9086", "传入的要审核的审核日志列表为空 "),
    UPDATE_ADJ_AUD_CHECK_TYPE_EMPTY("9087", "更新调帐审核日志，传入调帐类型为空 "),
    UPDATE_ADJ_AUD_CHECK_FLAG_EMPTY("9088", "更新调帐审核日志，传入调帐审核标识为空 "),
    UPDATE_ADJ_AUD_CHECK_STAFF_EMPTY("9089", "更新调帐审核日志，传入调帐员工标识为空 "),
    INVALID_ADJUST_CHECK_FLAG("9090", "无效的调帐审核标识 "),
    UPDATE_ADJ_AUD_CHECK_LOG_ID_EMPTY("9091", "更新调帐审核日志，传入调帐审核日志标识为空 "),
    ADJUST_AUDIT_QRY_FLAG_EMPTY("9092", "调帐审核日志查询，传入的查询标识为空 "),
    ADJUST_AUDIT_QRY_VALUE_EMPTY("9093", "调帐审核日志查询，传入的查询值为空 "),
    ADJUST_AUDIT_QRY_FOREADJUST_EMPTY("9094", "调帐审核日志查询，传入的否是帐前调帐标识为空 "),
    ADJUST_AUDIT_LOG_EMPTY("9095", "传入的调帐审核日志结构为空 "),
    ADJUST_AUD_LOG_FOREADJUST_EMPTY("9096", "调帐审核日志，帐前调帐标识为空 "),
    ADJUST_AUD_LOG_ADJ_TYPE_EMPTY("9097", "调帐审核日志，调帐类型为空 "),
    ADJUST_AUD_LOG_ADJ_CHARGE_EMPTY("9098", "调帐审核日志，调帐值为空 "),
    ADJUST_AUD_LOG_ACCT_ID_EMPTY("9099", "调帐审核日志，ACCTID为空 "),
    ADJUST_AUD_LOG_STAFF_EMPTY("9100", "调帐审核日志，STAFFID为空"),
    NO_OWE_CANNOT_ADJUST("9101", "该帐户没有欠费不能进行调帐 "),
    ADJUST_AUD_LOG_CYCLE_EMPTY("9102", "调帐审核日志，传入帐务周期为空"),
    ADJUST_AUD_LOG_CHARGE_EMPTY("9103", "按百分比调帐，指定的帐目类型金额为空 "),
    ADJUST_CHARGE_EXCEED_MAX("9104", "调帐之后，欠费变成负的，不能进行调帐 "),
    ADJ_HIS_QRY_ACCT_ID_EMPTY("9105", "查询历史调帐信息，传入ACCTID为空 "),
    ADJ_HIS_QRY_CYCLE_EMPTY("9106", "查询历史调帐信息，传入周期标识为空 "),
    ADJ_HIS_QRY_ADJ_ITEM_EMPTY("9107", "查询历史调帐信息，传入调帐帐目为空 "),
    ADJ_HIS_QRY_FORE_ADJ_EMPTY("9108", "查询历史调帐信息，传入是否帐前调帐标识为空 "),
    ITEM_CHARGE_QRY_ACCT_ID_EMPTY("9109", "查询帐目金额，传入ACCTID为空 "),
    ITEM_CHARGE_QRY_CYCLE_EMPTY("9110", "查询帐目金额，传入周期标识为空 "),
    ITEM_CHARGE_QRY_ITEM_ID_EMPTY("9111", "查询帐目金额，传入帐目类型标识为空 "),
    ADJUST_UNDO_ADJ_CHECK_EMPTY("9113", "调帐回退，传入的调帐审核结构为空 "),
    ADJUST_UNDO_CHECK_ID_LIST_EMPTY("9114", "调帐回退，传入的审核记录列表为空 "),
    ADJ_ACCT_ITEM_ID_ERROR_SELECT("9115", "调帐中获取ACCT_ITEM_ID出错 "),
    ADJ_ACCT_ITEM_ERROR_SELECT("9116", "调帐回退中查询状态为未销帐的帐目出错 "),
    ACCT_ITEM_AGGR_QUERY_EMPTY("9117", "帐前调帐查询帐目累计表结构为空 "),
    ACCT_ITEM_AGGR_QRY_SERV_EMPTY("9118", "帐前调帐查询帐目SERVID为空 "),
    ACCT_ITEM_AGGR_VECTOR_EMPTY("9119", "帐前调帐插入帐目信息列表为空 "),
    ADJUST_QUERY_EMPTY("9120", "传入调帐日志查询结构为空 "),
    INSERT_ADJUST_INFO_EMPTY("9121", "插入调帐日志，调帐信息结构为空 "),
    UPDATE_ADJ_LOG_ID_LIST_EMPTY("9122", "更新调帐日志，传入的日志标识列表为空 "),
    ADJUST_QUERY_FLAG_EMPTY("9123", "查询调帐日志，传入的查询标识为空 "),
    ADJUST_QUERY_VALUE_EMPTY("9124", "查询调帐日志，传入的查询值为空 "),
    ADJUST_QUERY_FOREADJUST_EMPTY("9125", "查询调帐日志，传入的是否帐前调帐调试为空 "),
    INVALID_ADJUST_QUERY_FLAG("9126", "无效的调帐日志查询标识 "),
    INSERT_ADJ_INFO_ACCT_EMPTY("9128", "插入调帐日志，传入的ACCTID为空 "),
    INSERT_ADJ_INFO_SERV_EMPTY("9129", "插入调帐日志，传入的SERVID为空"),
    INSERT_ADJ_INFO_ITEM_TYPE_EMPTY("9130", "插入调帐日志，传入调帐帐目类型为空"),
    INSERT_ADJ_INFO_ADJ_TYPE_EMPTY("9131", "插入调帐日志，传入调帐类型为空"),
    INSERT_ADJ_INFO_ADJ_CHARGE_EMPTY("9132", "插入调帐日志，传入调帐金额为空"),
    INSERT_ADJ_INFO_CYCLE_EMPTY("9133", "插入调帐日志，传入帐务周期为空"),
    INSERT_ADJ_INFO_STAFF_EMPTY("9134", "插入调帐日志，传入的操作员为空 "),
    INSERT_ADJ_INFO_REASON_EMPTY("9135", "插入调帐日志，传入的调帐原因为空"),
    INSERT_ADJ_INFO_AUD_ID_EMPTY("9136", "插入调帐日志，传入的审核日志标识为空"),
    INSERT_ADJ_INFO_STATE_EMPTY("9137", "插入调帐日志，传入的状态为空 "),
    INSERT_ADJ_INFO_ACCT_ITEM_EMPTY("9138", "插入调帐日志，传入是否帐前调帐标识为空"),
    INSERT_ADJ_INFO_FORE_ADJ_EMPTY("9139", "插入调帐日志，传入是否帐前调帐标识为空"),
    ACCT_ITEM_AGGR_QRY_ACCT_EMPTY("9140", "帐前调帐查询帐目ACCID为空 "),
    ADJUST_AUDIT_CHECK_TYPE_EMPTY("9141", "调帐审核，传入审核类型为空 "),
    ADJUST_AUDIT_CHECK_FLAG_EMPTY("9142", "调帐审核，传入审核标识为空 "),
    INVALID_ADJUST_AUDIT_CHECK_TYPE("9143", "调帐审核，无效的审核类型 "),
    ADJUST_APPLY_EMPTY("9144", "调帐申请结构为空 "),
    ADJUST_APPLY_FLAG_EMPTY("9145", "调帐申请，传入自动调帐标识为空 "),
    ADJUST_APPLY_ACCT_EMPTY("9146", "调帐申请，传入ACCTID为空 "),
    ADJUST_APPLY_SERV_EMPTY("9147", "调帐申请，传入SERVID为空 "),
    ADJUST_APPLY_CYCLE_EMPTY("9148", "调帐申请，传入帐务周期为空 "),
    ADJUST_APPLY_ADJ_ITEM_EMPTY("9149", "调帐申请，传入调帐帐目为空  "),
    ADJUST_APPLY_ADJ_TYPE_EMPTY("9150", "调帐申请，传入调帐类型为空 "),
    ADJUST_APPLY_ADJ_CHARGE_EMPTY("9151", "调帐申请，传入调帐值为空 "),
    ADJUST_APPLY_REASON_EMPTY("9152", "调帐申请，传入调帐原因为空 "),
    ADJUST_APPLY_STAFF_EMPTY("9153", "调帐申请，传入操作员标识为空 "),
    ADJUST_APPLY_FOREADJUST_EMPTY("9154", "调帐申请，传入是否帐前调帐标识为空 "),
    INVALID_ADJ_APPLY_FORE_ADJUST_FLAG("9155", "调帐申请，无效的帐前调帐标识 "),
    INVALID_ADJUST_AUDIT_FLAG_TYPE("9156", "调帐审核，无效的审核标识"),
    ADJUST_AUDIT_ADJ_CHECK_EMPTY("9157", "调帐审核，传入审核结构为空 "),
    DUE_ADJUST_HAVING_RECORD("9158", "该帐户已经存在一条违约金减免记录 "),
    DUE_ADJUST_APPLY_OWE_CHARGE_EMPTY("9159", "滞纳金减免申请，传入欠费金额为空"),
    DUE_ADJUST_BEYOND_STAFF_PRIVILIGE("9160", "违约金减免超出了员工的权限"),
    SELECT_A_DUE_ADJUST_LIMIT_ERROR("9161", "表A_DUE_ADJUST_LIMIT配置有问题"),
    DUE_ADJUST_APPLY_DUE_EMPTY("9162", "滞纳金减免申请，传入违约金为空"),
    LATE_FEE_COMPUTE_RULE_NOT_EXIST("9163", "滞纳金计算规则配置不存在 "),
    LATE_FEE_RATE_NOT_EXIST("9164", "滞纳金计算费率配置不存在 "),
    LATE_FEE_RATE_PROD_ID_NOT_EXIST("9165", "滞纳金计算费用产品实例没有对应产品"),
    STAFF_AUTH_SAME_TOO_MANY("10000", "员工管理有误,同一工号配给多人使用 "),
    STAFF_AUTH_INVALID_STAFF("10002", "工号不在生效时间范围内 "),
    STAFF_AUTH_ERROR_PASSWD("10003", "密码错误 "),
    STAFF_AUTH_ERROR_ROLE("10004", "员工无此权限 "),
    STAFF_AUTH_INVALID_ROLE("10005", "权限无效 "),
    STAFF_AUTH_CHECK_FAIL("10009", "插入STAFF_CHECK表失败 "),
    STAFF_AUTH_ROLE_EXP("10010", "权限不在生效时间范围内 "),
    STAFF_AUTH_ERROR_LOGON_DATE("10011", "工号登陆已经注销 "),
    STAFF_AUTH_ERROR_STAFF_LOGON("10012", "工号未经登录 "),
    STAFF_AUTH_ERROR_APP_NOTFOUND("10013", "找不到APP "),
    STAFF_CHECK_ERROR_NOT_LOGON("10014", "找不到登录信息无法轧帐 "),
    STAFF_ALREADY_CHECKED("10015", "员工已轧帐 "),
    ORG_RELATION_NOT_FOUND("10016", "运营机构和运维机构的对应关系未建"),
    STAFF_NOT_OPE_REGION("10017", "该员工不能管理这个运维机构 "),
    STAFF_NO_CASH_OTHER_BILL_REVERSE("10018", "该工号没有冲正他人付款的权限"),
    STAFF_NO_CASH_TERTIAN_BILL_REVERSE("10019", "该工号没有冲正隔日记录的权限"),
    STAFF_NO_OTHER_STAFF_CHECK_REVERSE("10020", "该工号没有反轧他人帐的权限 "),
    STAFF_NO_OTHER_STAFF_CHECK("10021", "该工号没有轧他人帐的权限 "),
    STAFF_LOGON_INVALID("10022", "工号被重复使用,本次登录已经失效 "),
    STAFF_NO_OTHER_BSS_ORG_REVERSE("10023", "该工号没有跨机构反销的权限 "),
    INVALID_ACCT_ITEM_UPDATE_VALUE_TYPE("10024", "无效的欠费帐目更新类型 "),
    BILL_ORDER_SET("10026", "请先反销后面的帐期或者该流水不存在 "),
    TRUST_BILL_NOT_ACTIVE_STATE("10033", "托收单状态不是托收状态 "),
    TRUST_NOT_EQUAL_ACCT_ITEM("10034", "托收单金额和托收帐目金额不相等"),
    TRUST_STATE_NOT_OWE_RECORD("10035", "托收单处于送托状态，但欠费帐目表没有对应的记录 "),
    TRUST_BILL_NOT_PAY_STATE("10036", "托收单状态不是销帐状态 "),
    TRUST_NOT_EQUAL_PAY_ITEM("10037", "托收单金额和托收销帐帐目金额不相等"),
    TRUST_BILL_NOT_CASH_STATE("10038", "托收单状态不是转现金状态 "),
    TRUST_BANK_NOT_FOUND("10040", "托收单不存在 "),
    ADJUST_AUDIT_INFO_NOT_FOUND("10041", "调帐审核信息未找到 "),
    ADJUST_AUDIT_LOG_ERROR_SELECT("10042", "查询调帐审核日志出错 "),
    ADJUST_AUDIT_LOG_ERROR_FETCH("10045", "获取调帐审核记录出错 "),
    NO_THIS_ACCT_ITEM("10049", "指定的帐目不存在 "),
    GET_PAYMETHOD_ERROR("10051", "获取帐户付款方式时出错 "),
    OWE_ERROR_MULTI_SERV("10052", "处理对象不唯一 "),
    OWE_NO_SERV_OR_EXT_SERV("10053", "处理对象为空 "),
    OWE_ERROR_INVALID_ACTION("10054", "无效的停开机动作 "),
    OWE_ERROR_ACTION_OUT_DISABLED("10055", "无效的可单停用户档案 "),
    OWE_ERROR_ACTION_DISABLED("10056", "无效的可双停用户档案 "),
    OWE_ERROR_ACTION_OUT_ENABLED("10057", "无效的可单开用户档案 "),
    OWE_ERROR_ACTION_ENABLED("10058", "无效的可双开用户档案 "),
    OWE_ERROR_ACTION_RESERVED("10059", "无效的可保号停机用户档案 "),
    OWE_ERROR_INVALID_URGE("10060", "无效的催缴动作 "),
    PASSWORD_MODIFY_LOOP_ERROR("10087", "密码5次内不得重复使用"),
    PASSWORD_MODIFY_COUNT_ERROR("10088", "每天密码不得修改5次以上"),
    OWE_TICKET_PROPERTY_VECTOR_EMPTY("20000", "10000号,通话清单查询中,没有对应条件的话单文件"),
    PROPERTY_ERROR_SELECT("20001", "10000号,通话清单查询中,话单文件选择有误"),
    CALL_CENTER_ERROR_OWETICKET_NOTFOUND("20002", "10000号,通话清单查询中,话单文件为空"),
    OWETICKET_ERROR_SELECT("20003", "10000号,通话清单查询中,话单内容选择有误"),
    CALL_CENTER_ERROR_CALL("20004", "10000号,通话清单查询中,中间件错误"),
    CALL_CENTER_ERROR_SERVID_NOTFOUND("20005", "10000号,套餐查询中,ServID不存在"),
    SERVID_ERROR_SELECT("20006", "10000号,套餐查询中,ServID选择有误"),
    CALL_CENTER_ERROR_SIGNDATE_NOTFOUND("20007", "10000号,套餐查询中,定购时间信息不存在"),
    SIGNDATE_ERROR_SELECT("20008", "10000号,套餐查询中,定购时间选择有误"),
    CALL_CENTER_ERROR_PRODUCTOFFER_NOTFOUND("20009", "10000号,套餐查询中,套餐属性信息不存在"),
    PRODUCTOFFER_ERROR_SELECT("20010", "10000号,套餐查询中,套餐属性选择有误"),
    CALL_CENTER_ERROR_ACCTID_NOTFOUND("20011", "10000号,月通话清单查询中,AcctID不存在"),
    ACCTID_ERROR_SELECT("20012", "10000号,月通话清单查询中,AcctID选择有误"),
    CALL_CENTER_ERROR_BILLREQUIREID_NOTFOUND("20013", "10000号,月通话清单查询中,BillRequireID不存在"),
    BILLREQUIREID_ERROR_SELECT("20014", "10000号,月通话清单查询中,BillRequireID选择有误"),
    CALL_CENTER_ERROR_BILLITEMTYPEID_NOTFOUND("20015", "10000号,月通话清单查询中,BillItemTypeID不存在"),
    BILLITEMTYPEID_ERROR_SELECT("20016", "10000号,月通话清单查询中,BillItemTypeID选择有误"),
    CALL_CENTER_ERROR_OWEITEMBILL_NOTFOUND("20017", "10000号,月通话清单查询中,通话帐单明细项不存在"),
    OWEITEMBILL_ERROR_SELECT("20018", "10000号,月通话清单查询中,通话帐单明细项选择有误"),
    CALL_CENTER_ERROR_RTCHARGEBILL_NOTFOUND("20019", "10000号,实时话费查询中,实时话费帐单明细项不存在"),
    RTCHARGEBILL_ERROR_SELECT("20020", "10000号,实时话费查询中,实时话费帐单明细项选择有误"),
    CALL_CENTER_ERROR_BEGINDATE_NOTFOUND("20021", "10000号,实时话费查询中,实时话费起始时间不存在"),
    BEGINDATE_ERROR_SELECT("20022", "10000号,实时话费查询中,实时话费起始时间选择有误"),
    CALL_CENTER_ERROR_ENDDATE_NOTFOUND("20023", "10000号,实时话费查询中,实时话费终止时间不存在"),
    ENDDATE_ERROR_SELECT("20024", "10000号,实时话费查询中,实时话费终止时间选择有误"),
    CALL_CENTER_ERROR_POINTSINFO_NOTFOUND("20025", "10000号,积分查询中,积分信息不存在"),
    POINTSINFO_ERROR_SELECT("20026", "10000号,积分查询中,积分信息选择有误"),
    CALL_CENTER_ERROR_ACCTNBR97_NOTFOUND("20027", "10000号,预存话费余额查询中,97合同号不存在"),
    ACCTNBR97_ERROR_SELECT("20028", "10000号,预存话费余额查询中,97合同号选择有误"),
    CALL_CENTER_ERROR_ACCNBR_NOTFOUND("20029", "10000号,预存话费余额查询中,电话号码不存在"),
    ACCNBR_ERROR_SELECT("20030", "10000号,预存话费余额查询中,电话号码选择有误"),
    CALL_CENTER_ERROR_BALANCETYPENAME_NOTFOUND("20031", "10000号,预存话费余额查询中,余额类型名称不存在"),
    BALANCETYPENAME_ERROR_SELECT("20032", "10000号,预存话费余额查询中,余额类型名称选择有误"),
    CALL_CENTER_ERROR_SMCRESULT_NOTFOUND("20033", "10000号,短信话单查询中,短信话单不存在"),
    SMCRESULT_ERROR_SELECT("20034", "10000号,短信话单查询中,短信话单选择有误"),
    CALL_CENTER_ERROR_TONECODERESULT_NOTFOUND("20035", "10000号,彩铃查询中,彩铃信息不存在"),
    TONECODERESULT_ERROR_SELECT("20036", "10000号,彩铃查询中,彩铃信息选择有误"),
    CALL_CENTER_ERROR_SPRESULT_NOTFOUND("20037", "10000号,SP查询中,SP信息不存在"),
    SPRESULT_ERROR_SELECT("20038", "10000号,SP查询中,SP信息选择有误"),
    SELECT_SERV_AVERAGE_FEE_ERROR("20039", "10000号,query average fee error"),
    CHECK_ERROR_IN_AUTH_ID("30000", "申请时认证号不正确 "),
    APPLY_ID_NOT_FOUND("30001", "根据申请号找不到退款申请信息 "),
    APPLY_INFO_OPPOSE_STATE("30002", "审核时前后状态不匹配 "),
    APPLY_INFO_EXIST_FOR_DONE("30003", "已经存在申请审核或已审核的申请单,请先到营业前台退款 "),
    APPLY_INFO_STATE_ERROR("30010", "退款申请单状态不匹配 "),
    STATE_NOT_BILL_PAY("30018", "代收打发票为非销帐状态"),
    TRUST_INVOICE_PRINT_EMPTY("30019", "传入是否打代收发票标识为空"),
    FIRST_PRINT_STAFF_IS_NULL("30020", "第一次打印发票员工号为空"),
    SITE_ALREADY_CONTROL("40000", "当前不可以收费,系统可能正在出帐 "),
    SITE_ALREADY_CHECK("40001", "营业点已轧帐 "),
    CHECK_STAFF_NOT_SAME_ORG("40002", "轧帐的两个工号不属于同一个营业机构 "),
    SITE_NOT_CHECKED("40003", "营业点未轧帐 "),
    STAFF_NOT_CHECKED("40008", "员工未轧帐 "),
    CANNOT_TERTIAN_CHECK_REVERSE("40009", "不能隔日反轧帐 "),
    STAFF_NO_SITE_CHECK("40010", "该员工号没有营业点轧帐的权限 "),
    STAFF_NO_SITE_CHECK_REVERSE("40011", "该员工号没有营业点反轧帐的权限 "),
    LOGON_LIMIT_ERR("40012", "该员工号登陆有限制 "),
    CHARGE_NOT_EQUAL_DETAIL("40050", "退款时退款金额与帐本退款明细不符 "),
    CLEAR_OWE_BEFORE_REFUND("40051", "请先缴清欠费再退款 "),
    CLEAR_OWE_BEFORE_RTVIREMENT("40052", "请先缴清欠费再做立即结帐"),
    STAFF_NOT_BELONG_AGENT("40100", "该员工号不是代缴工号,请向电信咨询"),
    AGENT_OPEN_FILE_ERROR("40101", "打开文件出错,请检查银行目录是否具有写权限 "),
    AGENT_VS_DELETE_ERROR("40102", "删除对帐数据出错 "),
    AGENT_VS_INSERT_ERROR("40103", "插入对帐数据出错 "),
    FILE_HAS_EXISTED("40104", "输出文件已经存在,可能已经做过该操作 "),
    FILE_HAS_NOT_EXISTED("40105", "查询文件不存在,检查是否做过查询操作 "),
    RECORD_NOT_FIND("40106", "缴费记录不存在于查询结果中，请对比查询结果和缴费文件 "),
    INVALIDE_SERVICE_CODE("40109", "不正确的银行服务代码"),
    INSERT_A_DEPOSIT_IN_ERR("40110", "40110"),
    GET_SQLTEXT_ERROR("50000", "待完错误描述"),
    BATCH_BILL_BILLING_CYCLE_MISS("50002", "待完错误描述"),
    BATCH_BILL_BATCH_ID_MISS("50003", "待完错误描述"),
    BATCH_BILL_ACCT_ID_MISS("50004", "待完错误描述"),
    BATCH_REVERSE_MISS_STAFF("50005", "待完错误描述"),
    BATCH_REVERSE_MISS_PAYMENT("50006", "待完错误描述"),
    BATCH_INVOICE_MISS_PAYMENT("50007", "待完错误描述"),
    BATCH_INVOICE_MISS_STAFF("50008", "待完错误描述"),
    BATCH_INVOICE_MISS_CYCLE("50009", "待完错误描述"),
    BATCH_INVOICE_MISS_FLAG("50010", "待完错误描述"),
    BATCH_INVOICE_MISS_ACC_NBR("50011", "待完错误描述"),
    A_BATCH_BILL_PAYMENT_NOT_EXIST("50012", "待完错误描述"),
    BATCH_BILL_DEPOSIT_MISS("50014", "待完错误描述"),
    INVLID_PASSWD_OFF_DAY("60000", "密码过期失效 "),
    INVLID_PASSWD_COMPLEXITY("60001", "密码复杂度验证失败 "),
    QUERY_ERROR_ACCTID_NOTFOUND("70003", "查询等级未找到"),
    A_ERROR_DEPOSIT_FLAG("70004", "70004"),
    INSERT_BILL_PAYMENT_ID_EMPTY("402401", "插入销帐记录表, 交易流水为空 "),
    INSERT_BILL_ORG_ID_EMPTY("402402", "插入销帐记录表, 电信组织标识为空 "),
    SELECT_PHONE_RETURN_INST_ERROR("609000", "查询红包返还实例出错 "),
    PHONE_RETURN_INPUT_BILLING_CYCLE_ID("609001", "未获取有效账期ID "),
    PHONE_RETURN_INPUT_BILL_ID("609002", "未获取有效销账流水ID "),
    INSERT_PHONE_RETURN_BUDGET_API_ERROR("609003", "插入红包返还估算日志报错"),
    INSERT_PHONE_RETURN_CALC_API_ERROR("609004", "插入红包返还实算日志报错"),
    PHONE_RETURN_INPUT_ACCT_ID("609005", "输入帐户ID有误 "),
    PHONE_RETURN_LEFT_AMOUNT_NONE("609006", "红包返还实例可以返还金额为零 "),
    PHONE_RETURN_INPUT_OFFER_TYPE("609007", "获取返费类型有误 "),
    BIND_ADSL_NOT_EXIST("1000000", "该账户没有绑定ADSL"),
    INSERT_CHARGE_SEQ_ERR("1000002", "插入充值序列号出错"),
    AFFERENT_FLAG_ERR("1000003", "待完错误描述"),
    ACCT_ID_IS_NULL("1000004", "待完错误描述"),
    UPDATE_AGENT_VS_ERROR("1000010", "更改AGENT_VS表中pay_serial_nbr=0的记录出错"),
    DELETE_A_BILL_VS_ERR("1000011", "删除电信对帐表中关于本银行的对帐数据出错"),
    INSERT_A_BILL_VS_ERR("1000012", "插入电信对帐表中关于本银行的对帐数据出错"),
    INSERT_A_AGENT_VS_RESULT_ERR("1000013", "生成不平数据出错"),
    QRY_A_AGENT_VS_RESULT_ERR("1000014", "取出A_AGENT_VS_RESULT表中的数据出错"),
    UPDATE_REVERSE_STATE_ERR("1000015", "设置可以批量反销的号码出错"),
    UPDATE_BILL_STATE_ERR("1000016", "设置可以批量销账的号码出错"),
    INSERT_A_AGENT_VS_RESULT_LOG_ERR("1000017", "插入对帐结果日志表出错"),
    UPDATE_BILL_DATE_ERR("1000018", "修改销帐表的时间出错"),
    UPDATE_PAYMENT_DATE_ERR("1000019", "修改付款表的时间出错"),
    CALL_AGENT_VS_SPRESULT_NOTFOUND("1000020", "没有单边账"),
    DELETE_A_AGENT_VS_RESULT_ERR("1000021", "没有单边账"),
    SELECT_EFFDATE_ERR("1000022", "绵阳:取充值卡有效期失败"),
    SELECT_BILLINGMODEID_ERR("1000023", "绵阳:取billing_mode_id出错"),
    UPDATE_EFFDATE_ERR("1000024", "绵阳:修改有效期出错"),
    SELECT_EFFDATE_MODE_ERR("1000025", "绵阳:取处理有效期方式出错"),
    DELETE_EFFDATE_ERR("1000026", "绵阳:取出时间并UPDATE为空出错"),
    RENEW_EXPDATE_ERR("1000027", "绵阳:恢复为原先的时间"),
    CHECK_PASSWORD_ERR("1000028", "非本机查询密码验证错误"),
    GET_CONFER_DETAIL_ERR("1000029", "取赠送规则出错"),
    GET_CONFER_CHARGE_ERR("1000030", "取赠送金额出错 "),
    RECHARGE_CARD_TYPE_EMPTY("1000040", "充值卡类型为空"),
    CARD_TYPE_UNIQUE_BALANCE_TYPE("1000041", "充值卡类型没有对应的余额类型"),
    CARD_TYPE_MANY_BALANCE_TYPE("1000042", "一种充值卡类型对应多种余额类型"),
    CARD_GROUP_ID_UNIQUE("1000043", "充值卡准备冲入的专款专用类型与配置表不一致"),
    INSERT_CONFER_LOG_ACCT_ID_EMPTY("1000044", "待完错误描述"),
    INSERT_CONFER_LOG_PAYMENT_ID_EMPTY("1000045", "待完错误描述"),
    INSERT_CONFER_LOG_CONFER_VALUE_EMPTY("1000046", "待完错误描述"),
    NON_BALANCE_TYPE_ID("1000047", "传入的余额类型在计费余额类型表中不存在"),
    NON_ACCT_ITEM_GROUP_ID("1000048", "传入的账目组在计费配置表中不存在"),
    BSS_ORG_TOO_LONG("1100000", "待完错误描述"),
    NO_CARD_PAYMENT_BILL_INFO("1100007", "待完错误描述"),
    PRINT_ACCT_ID_EMPTY("1100013", "待完错误描述"),
    PRINT_SERV_ID_EMPTY("1100014", "待完错误描述"),
    NO_CUST_POINTS_INFO("1100016", "待完错误描述"),
    BILL_ID_MISMATCH("1100018", "待完错误描述"),
    SELECT_ING_REPORT_ERROR("1100020", "待完错误描述"),
    ERROR_FILE_VERSION("1100027", "待完错误描述"),
    SELECT_CHECK_STATE_ERROR("1100028", "待完错误描述"),
    SELECT_TRANS_ERROR("1100029", "待完错误描述"),
    SELECT_DRAW_ERROR("1100030", "待完错误描述"),
    EXIST_UNBILLED_ACCT_ITEM("1100032", "待完错误描述"),
    ERROR_GRITID("1100042", "非费用账单项费用账目粒度标识<>1"),
    ERROR_GRIT_TYPE("1100043", "错误的粒度类型"),
    SAME_INCOME_MORE("1100048", "待完错误描述"),
    NOT_PRINT_FOR_5KR("1100050", "待完错误描述"),
    MOBILE_BILLING_TYPE_NOT_ALLOW("1110001", "小灵通计费类型(billing_mode)不允许充值"),
    PHONE_BILLING_TYPE_NOT_ALLOW("1110002", "村村通,金蓉通不允许银行充值"),
    FC_NO_SERV("201", "充值用户不存在"),
    FC_NO_ROLE("202", "用户没权限充值"),
    STAFF_BLOCK_HINT("20130321002","当日连续输入错误密码次数达到10次，帐号已经被锁定，请联系管理员解锁 "),
    DATASOURCE_ROUTE_FAILED("-100", "未定位到数据源");


    /**
     * 状态码
     */
    private String code;

    /**
     * 提示信息
     */
    private String message;

    /**
     * 构造函数
     *
     * @param code    状态码
     * @param message 提示信息
     */
    ErrorCodePublicEnum(String code, String message) {
        this.code = code;
        this.message = message;
    }

    /**
     * 获取状态码
     *
     * @return 状态码
     */
    @Override
    public String getCode() {
        return this.code;
    }

    /**
     * 获取提示信息
     *
     * @return 提示信息
     */
    @Override
    public String getMessage() {
        return this.message;
    }
}
